from bcap.util.bcap_aliases import AbstractAliases


class ArchaeologicalSiteAliases(AbstractAliases):
    ACCURACY_REMARKS = "accuracy_remarks"
    ADDRESS_REMARKS = "address_remarks"
    ALERT_BRANCH_CONTACT = "alert_branch_contact"
    ALERT_DETAILS = "alert_details"
    ALERT_ENTERED_BY = "alert_entered_by"
    ALERT_ENTRY_DATE = "alert_entry_date"
    ALERT_SUBJECT = "alert_subject"
    ASSIGNED_OR_REPORTED_BY = "assigned_or_reported_by"
    ASSIGNED_OR_REPORTED_DATE = "assigned_or_reported_date"
    AUTHORITY_DESCRIPTION = "authority_description"
    AUTHORITY_END_DATE = "authority_end_date"
    AUTHORITY_LEGAL_INSTRUMENT = "authority_legal_instrument"
    AUTHORITY_PROTECTION_TYPE = "authority_protection_type"
    AUTHORITY_START_DATE = "authority_start_date"
    BCAP_SUBMISSION_STATUS = "bcap_submission_status"
    BIOGEOGRAPHY_DESCRIPTION = "biogeography_description"
    BIOGEOGRAPHY_NAME = "biogeography_name"
    BIOGEOGRAPHY_TYPE = "biogeography_type"
    BORDEN_NUMBER = "borden_number"
    BORDEN_NUMBER_ISSUANCE_DATE = "borden_number_issuance_date"
    CITY = "city"
    CONTRAVENTION_ADDRESS = "contravention_address"
    CONTRAVENTION_DOCUMENT = "contravention_document"
    CONTRAVENTION_PID = "contravention_pid"
    CONVICTION_DATE = "conviction_date"
    CONVICTION_DETAILS = "conviction_details"
    COPYRIGHT = "copyright"
    DECISION_DATE = "decision_date"
    DECISION_DESCRIPTION = "decision_description"
    DECISION_MADE_BY = "decision_made_by"
    DECISION_REGISTRATION_STATUS = "decision_registration_status"
    ELEVATION_COMMENTS = "elevation_comments"
    EXTERNAL_URL = "external_url"
    EXTERNAL_URL_TYPE = "external_url_type"
    GENERAL_REMARK = "general_remark"
    GENERAL_REMARK_DATE = "general_remark_date"
    GENERAL_REMARK_SOURCE = "general_remark_source"
    GIS_LOWER_ELEVATION = "gis_lower_elevation"
    GIS_UPPER_ELEVATION = "gis_upper_elevation"
    IMAGE_DATE = "image_date"
    IMAGE_DESCRIPTION = "image_description"
    IMAGE_FEATURES = "image_features"
    IMAGE_TYPE = "image_type"
    IMAGE_VIEW = "image_view"
    INVENTORY_REMARK = "inventory_remark"
    LATEST_EDIT_TYPE = "latest_edit_type"
    LEGAL_ADDRESS_REMARKS = "legal_address_remarks"
    LEGAL_DESCRIPTION = "legal_description"
    LEGISLATIVE_ACT = "legislative_act"
    NAME = "name"
    NAME_REMARKS = "name_remarks"
    NAME_TYPE = "name_type"
    NROS_FILE_NUMBER = "nros_file_number"
    PARCEL_OWNER_TYPE = "parcel_owner_type"
    PARENT_SITE = "parent_site"
    PHOTOGRAPHER = "photographer"
    PID = "pid"
    PIN = "pin"
    POSTAL_CODE = "postal_code"
    PRIMARY_IMAGE = "primary_image"
    PUBLICATION_REFERENCE = "publication_reference"
    RECOMMENDATION_DATE = "recommendation_date"
    RECOMMENDED_BY = "recommended_by"
    REFERENCE_NUMBER = "reference_number"
    REGISTER_TYPE = "register_type"
    RELATED_DOCUMENT_DESCRIPTION = "related_document_description"
    RELATED_DOCUMENT_TYPE = "related_document_type"
    RELATED_SITE_DOCUMENTS = "related_site_documents"
    REMAINS_REMARK_ENTRY_DATE = "remains_remark_entry_date"
    REMAINS_REMARK_MADE_BY = "remains_remark_made_by"
    REMARK_KEYWORD = "remark_keyword"
    RESPONSIBLE_GOVERNMENT = "responsible_government"
    RESTRICTED = "restricted"
    RESTRICTED_ANCESTRAL_REMAINS_REMARK = "restricted_ancestral_remains_remark"
    RESTRICTED_DOCUMENT = "restricted_document"
    RESTRICTED_ENTRY_DATE = "restricted_entry_date"
    RESTRICTED_PERSON = "restricted_person"
    RESTRICTED_REMARK = "restricted_remark"
    SITE_BOUNDARY = "site_boundary"
    SITE_BOUNDARY_DESCRIPTION = "site_boundary_description"
    SITE_DECISION = "site_decision"
    SITE_IMAGES = "site_images"
    SITE_TENURE_IDENTIFIER = "site_tenure_identifier"
    SITE_TENURE_REMARKS = "site_tenure_remarks"
    SITE_TENURE_TYPE = "site_tenure_type"
    STREET_NAME = "street_name"
    STREET_NUMBER = "street_number"
    TYPOLOGY_CLASS = "typology_class"
    TYPOLOGY_REMARK = "typology_remark"
    UNPROTECTED_AREAS = "unprotected_areas"

    @staticmethod
    def get_aliases():
        return AbstractAliases.get_dict(ArchaeologicalSiteAliases)


class ArchaeologicalSiteGroupAliases(AbstractAliases):
    ANCESTRAL_REMAINS = "ancestral_remains"
    ARCHAEOLOGICAL_DATA = "archaeological_data"
    AUTHORITY = "authority"
    BC_PROPERTY_ADDRESS = "bc_property_address"
    BC_PROPERTY_LEGAL_DESCRIPTION = "bc_property_legal_description"
    BIOGEOGRAPHY = "biogeography"
    CONVICTION = "conviction"
    ELEVATION = "elevation"
    GENERAL_REMARK_INFORMATION = "general_remark_information"
    HCA_CONTRAVENTION = "hca_contravention"
    HERITAGE_SITE_LOCATION = "heritage_site_location"
    IDENTIFICATION_AND_REGISTRATION = "identification_and_registration"
    RELATED_DOCUMENTS = "related_documents"
    REMARKS_AND_RESTRICTED_INFORMATION = "remarks_and_restricted_information"
    RESTRICTED_INFORMATION = "restricted_information"
    SITE_ALERT = "site_alert"
    SITE_NAMES = "site_names"
    SITE_RECORD_ADMIN = "site_record_admin"
    SITE_TENURE = "site_tenure"
    SITE_TYPOLOGY = "site_typology"

    @staticmethod
    def get_aliases():
        return AbstractAliases.get_dict(ArchaeologicalSiteGroupAliases)
