from bcap.util.bcap_aliases import AbstractAliases


class HriaDiscontinuedDataAliases(AbstractAliases):
    ACCURACY_REMARKS = "accuracy_remarks"
    ARCHAEOLOGICAL_SITE = "archaeological_site"
    BIOGEOGRAPHY_DESCRIPTION = "biogeography_description"
    BIOGEOGRAPHY_ENTERED_BY = "biogeography_entered_by"
    BIOGEOGRAPHY_ENTERED_DATE = "biogeography_entered_date"
    BIOGEOGRAPHY_NAME = "biogeography_name"
    BIOGEOGRAPHY_TYPE = "biogeography_type"
    BOUNDARY_TYPE = "boundary_type"
    CHRONOLOGY_REMARKS = "chronology_remarks"
    DETERMINATION_METHOD = "determination_method"
    DIMENSION_ENTERED_BY = "dimension_entered_by"
    DIMENSION_ENTERED_DATE = "dimension_entered_date"
    END_YEAR_CALENDAR = "end_year_calendar"
    END_YEAR = "end_year"
    END_YEAR_QUALIFIER = "end_year_qualifier"
    ENTERED_BY = "entered_by"
    ENTERED_ON = "entered_on"
    INFORMATION_SOURCE = "information_source"
    JURISDICTION_ENTERED_BY = "jurisdiction_entered_by"
    JURISDICTION_ENTERED_DATE = "jurisdiction_entered_date"
    LENGTH_DIRECTION = "length_direction"
    LENGTH = "length"
    MODIFIED_BY = "modified_by"
    MODIFIED_ON = "modified_on"
    NEW_NODE = "new_node"
    OTHER_MAPS_MAP_NAME = "other_maps_map_name"
    OTHER_MAPS_MAP_SCALE = "other_maps_map_scale"
    OTHER_MAPS_MODIFIED_BY = "other_maps_modified_by"
    OTHER_MAPS_MODIFIED_ON = "other_maps_modified_on"
    RCD_ADJUSTED = "rcd_adjusted"
    RCD_ADJUSTED_VAR = "rcd_adjusted_var"
    RCD_LAB_CODE = "rcd_lab_code"
    RCD_LAB_NUMBER = "rcd_lab_number"
    RCD_UNADJUSTED = "rcd_unadjusted"
    RCD_UNADJUSTED_VAR = "rcd_unadjusted_var"
    SITE_AREA = "site_area"
    SITE_ENTERED_BY = "site_entered_by"
    SITE_ENTRY_DATE = "site_entry_date"
    SITE_JURISDICTION = "site_jurisdiction"
    SOURCE_NOTES = "source_notes"
    START_YEAR_CALENDAR = "start_year_calendar"
    START_YEAR_QUALIFIER = "start_year_qualifier"
    START_YEAR = "start_year"
    TENURE_IDENTIFIER = "tenure_identifier"
    TENURE_REMARKS = "tenure_remarks"
    TENURE_TYPE = "tenure_type"
    UNREVIEWED_ADIF_RECORD = "unreviewed_adif_record"
    WIDTH_DIRECTION = "width_direction"
    WIDTH = "width"

    @staticmethod
    def get_aliases():
        return AbstractAliases.get_dict(HriaDiscontinuedDataAliases)
