from bcap.util.bcap_aliases import AbstractAliases


class PermitApplicationAliases(AbstractAliases):
    ADDITIONAL_COLLECTION_AND_SAMPLING_DETAILS = (
        "additional_collection_and_sampling_details"
    )
    ADDITIONAL_RECORDING_INFORMATION = "additional_recording_information"
    ADDITIONAL_REPOSITORY_AND_CURATION_COMMENTS = (
        "additional_repository_and_curation_comments"
    )
    AFFECTED_SITES = "affected_sites"
    ALTERATION_DETAILS = "alteration_details"
    ALTERNATE_ANCESTRAL_REMAINS_APPROACH = "alternate_ancestral_remains_approach"
    ALTERNATE_CMT_APPROACH = "alternate_cmt_approach"
    ALTERNATE_EXCAVATION_APPROACH = "alternate_excavation_approach"
    ALTERNATE_HISTORICAL_SITES_APPROACH = "alternate_historical_sites_approach"
    ALTERNATE_ROCK_ART_RECORDING_APPROACH = "alternate_rock_art_recording_approach"
    ALTERNATE_SITE_FLAGGING_APPROACH = "alternate_site_flagging_approach"
    ALTERNATE_WET_SITES_APPROACH = "alternate_wet_sites_approach"
    ANCESTRAL_REMAINS_APPROACH_ADDITIONAL_COMMENTS = (
        "ancestral_remains_approach_additional_comments"
    )
    ANCESTRAL_REMAINS_APPROACH_COMPLIANT = "ancestral_remains_approach_compliant"
    ANCESTRAL_REMAINS_APPROACH_METHODS = "ancestral_remains_approach_methods"
    APPLICANT_NAME = "applicant_name"
    APPLICATION_ARCHAEOLOGIST = "application_archaeologist"
    APPLICATION_ID = "application_id"
    APPLICATION_PRIORITY_LEVEL = "application_priority_level"
    APPLICATION_PROPONENT = "application_proponent"
    APPLICATION_SUBMISSION_DATE = "application_submission_date"
    APPROACH_ON_CONCURRENT_PERMITS = "approach_on_concurrent_permits"
    ARCH_BEARING_SEDIMENT = "arch_bearing_sediment"
    ARCH_POTENTIAL_APPROACH = "arch_potential_approach"
    ARCH_WORKPLANS_AND_SCHEDULE_A = "arch_workplans_and_schedule_a"
    ARE_ANCESTRAL_REMAINS_ANTICIPATED = "are_ancestral_remains_anticipated"
    ARE_CHANCE_FINDS_EXPECTED = "are_chance_finds_expected"
    ASSESSMENT_APPROACH = "assessment_approach"
    COLLECTION_APPROACH = "collection_approach"
    COLLECTION_APPROACH_ADDITIONAL_COMMENTS = "collection_approach_additional_comments"
    COLLECTION_APPROACH_DETAILS = "collection_approach_details"
    CONCURRENT_PERMITS_LIST = "concurrent_permits_list"
    COPYRIGHT_AUTHORIZATION = "copyright_authorization"
    DATA_ANALYSIS_METHODS = "data_analysis_methods"
    DESTINATION_REPOSITORY = "destination_repository"
    DETAILS_OF_COLLECTED_MATERIALS = "details_of_collected_materials"
    DETAILS_OF_COLLECTED_SAMPLES = "details_of_collected_samples"
    FIELD_DIRECTORS = "field_directors"
    FIELD_TRANSPORT_AND_LAB_METHODS = "field_transport_and_lab_methods"
    FN_FILE_NUMBERS = "fn_file_numbers"
    GRANT_OF_LICENSE_TO_MINISTRY = "grant_of_license_to_ministry"
    HAS_ARCH_POTENTIAL = "has_arch_potential"
    HAS_CMT_SURVEY = "has_cmt_survey"
    HAS_CONCURRENT_PERMITS = "has_concurrent_permits"
    HAS_FN_ENDORSEMENTS = "has_fn_endorsements"
    HAS_HISTORICAL_SITES = "has_historical_sites"
    HAS_MACHINE_ASSISTED_INSPECTION = "has_machine_assisted_inspection"
    HAS_PRE_FIELD_RESEARCH = "has_pre_field_research"
    HAS_REPOSITORY_AGREEMENT = "has_repository_agreement"
    HAS_REPOSITORY_BEEN_CONTACTED = "has_repository_been_contacted"
    HAS_RETAINED_ARCHAEOLOGIST = "has_retained_archaeologist"
    HAS_SITE_FLAGGING = "has_site_flagging"
    HAS_SUBSURFACE_TESTING = "has_subsurface_testing"
    HAS_SURVEY_COVERAGE = "has_survey_coverage"
    HAS_WET_SITES = "has_wet_sites"
    HAS_WINTER_ASSESSMENTS = "has_winter_assessments"
    HIP_OBJECTIVES = "hip_objectives"
    HIP_STUDY_DETAILS = "hip_study_details"
    INDUSTRIAL_SECTOR = "industrial_sector"
    IS_CONSENT_GIVEN = "is_consent_given"
    IS_EXCAVATION_APPROACH_COMPLIANT = "is_excavation_approach_compliant"
    IS_HCA_COMPLIANT = "is_hca_compliant"
    IS_RELATED_PERMIT = "is_related_permit"
    IS_REPLACEMENT = "is_replacement"
    IS_REPOSITORY_REQUIRED = "is_repository_required"
    IS_ROCK_ART_RECORDING_COMPLIANT = "is_rock_art_recording_compliant"
    MACHINE_ASSISTED_INSPECTION_APPROACH = "machine_assisted_inspection_approach"
    MACHINE_ASSISTED_INSPECTION_METHODS = "machine_assisted_inspection_methods"
    MAP_OR_HIP = "map_or_hip"
    METHODS_ALIGNMENT = "methods_alignment"
    MINISTRY_ASSIGNEE = "ministry_assignee"
    MITIGATION_MEASURES = "mitigation_measures"
    MZA_ALTERATION_DETAILS = "mza_alteration_details"
    MZA_INDUSTRIAL_SECTOR = "mza_industrial_sector"
    MZA_PROJECT_BOUNDARY = "mza_project_boundary"
    MZA_PROJECT_DESCRIPTION = "mza_project_description"
    MZA_PROJECT_TYPE = "mza_project_type"
    MZA_REQUIREMENT = "mza_requirement"
    MZA_REQUIREMENT_MINISTRY_ASIGNEE = "mza_requirement_ministry_asignee"
    MZA_SCOPE_OF_WORK = "mza_scope_of_work"
    OTHER_FIELD_METHODS = "other_field_methods"
    OTHER_RECORDING_APPROACHES = "other_recording_approaches"
    OVERSEEING_ARCHAEOLOGIST = "overseeing_archaeologist"
    PERMIT_DELIVERABLES = "permit_deliverables"
    PERMIT_DURATION_YEARS_REQUESTED = "permit_duration_years_requested"
    PROCESS_REQUIREMENT = "process_requirement"
    PROCESS_REQUIREMENT_ORDER = "process_requirement_order"
    PROJECT_BOUNDARY = "project_boundary"
    PROJECT_DESCRIPTION = "project_description"
    PROJECT_NAME = "project_name"
    PROJECT_OFFICER = "project_officer"
    PROJECT_TYPE = "project_type"
    RATIONALE_FOR_NO_ARCHAEOLOGIST = "rationale_for_no_archaeologist"
    RELATED_ASSESSMENTS = "related_assessments"
    RELATED_PERMIT = "related_permit"
    RELEVANT_ARCH_STUDIES = "relevant_arch_studies"
    RESPONSIBLE_EXTERNAL_ARCHAEOLOGIST = "responsible_external_archaeologist"
    SCOPE_OF_WORK = "scope_of_work"
    SUBSURFACE_TESTING_APPROACH = "subsurface_testing_approach"
    SUPPLEMENTAL_INFORMATION = "supplemental_information"
    SURVEY_COVERAGE_APPROACH = "survey_coverage_approach"
    TIME_OF_CONSENT = "time_of_consent"
    WINTER_ASSESSMENT_METHODS = "winter_assessment_methods"

    @staticmethod
    def get_aliases():
        return AbstractAliases.get_dict(PermitApplicationAliases)
