from bcap.util.bcap_aliases import AbstractAliases


class SiteVisitAliases(AbstractAliases):
    ACCURACY_REMARKS = "accuracy_remarks"
    AFFILIATION = "affiliation"
    ANCESTRAL_REMAINS_REMARKS = "ancestral_remains_remarks"
    ANCESTRAL_REMAINS_REPOSITORY = "ancestral_remains_repository"
    ANCESTRAL_REMAINS_STATUS = "ancestral_remains_status"
    ANCESTRAL_REMAINS_TYPE = "ancestral_remains_type"
    ARCHAEOLOGICAL_CULTURE = "archaeological_culture"
    ARCHAEOLOGICAL_FEATURE = "archaeological_feature"
    ARCHAEOLOGICAL_SITE = "archaeological_site"
    ARCHAEOLOGY_BRANCH_RECOMMENDATION = "archaeology_branch_recommendation"
    ASSIGNED_OR_REPORTED_BY = "assigned_or_reported_by"
    ASSIGNED_OR_REPORTED_DATE = "assigned_or_reported_date"
    ASSOCIATED_PERMIT = "associated_permit"
    BIOGEOGRAPHY_DESCRIPTION = "biogeography_description"
    BIOGEOGRAPHY_NAME = "biogeography_name"
    BIOGEOGRAPHY_TYPE = "biogeography_type"
    CHRONOLOGY_REMARKS = "chronology_remarks"
    CULTURAL_MATERIAL_DETAILS = "cultural_material_details"
    CULTURAL_MATERIAL_STATUS = "cultural_material_status"
    CULTURAL_MATERIAL_TYPE = "cultural_material_type"
    CULTURE_REMARKS = "culture_remarks"
    DETERMINATION_METHOD = "determination_method"
    DISTURBANCE_CAUSE = "disturbance_cause"
    DISTURBANCE_PERIOD = "disturbance_period"
    DISTURBANCE_REMARKS = "disturbance_remarks"
    END_YEAR_CALENDAR = "end_year_calendar"
    END_YEAR = "end_year"
    END_YEAR_QUALIFIER = "end_year_qualifier"
    FEATURE_COUNT = "feature_count"
    FEATURE_REMARKS = "feature_remarks"
    FIRST_DATE_OF_SITE_VISIT = "first_date_of_site_visit"
    INFORMATION_SOURCE = "information_source"
    LAST_DATE_OF_SITE_VISIT = "last_date_of_site_visit"
    LATEST_EDIT_TYPE = "latest_edit_type"
    LOCATION_AND_ACCESS = "location_and_access"
    MEMBER_ROLES = "member_roles"
    MINIMUM_NUMBER_OF_INDIVIDUALS = "minimum_number_of_individuals"
    MULTIPLE_BURIALS = "multiple_burials"
    NAME = "name"
    NAME_REMARKS = "name_remarks"
    NAME_TYPE = "name_type"
    NONPERMITTED_SITE_VISIT = "nonpermitted_site_visit"
    NUMBER_OF_ARTIFACTS = "number_of_artifacts"
    PROJECT_DESCRIPTION = "project_description"
    RECOMMENDED_UNPROTECTED_AREAS = "recommended_unprotected_areas"
    RECORDERS_RECOMMENDATION = "recorders_recommendation"
    REMARK_DATE = "remark_date"
    REMARK = "remark"
    REMARK_SOURCE = "remark_source"
    REPOSITORY = "repository"
    SITE_FORM_AUTHORS = "site_form_authors"
    SITE_VISIT_LOCATION = "site_visit_location"
    SITE_VISIT_TYPE = "site_visit_type"
    SOURCE_NOTES = "source_notes"
    START_YEAR_CALENDAR = "start_year_calendar"
    START_YEAR_QUALIFIER = "start_year_qualifier"
    START_YEAR = "start_year"
    STRATIGRAPHY = "stratigraphy"
    TEAM_MEMBER = "team_member"
    TEMPORARY_NUMBER_ASSIGNED_BY = "temporary_number_assigned_by"
    TEMPORARY_NUMBER_ASSIGNED_DATE = "temporary_number_assigned_date"
    TEMPORARY_NUMBER = "temporary_number"
    WAS_ON_SITE = "was_on_site"

    @staticmethod
    def get_aliases():
        return AbstractAliases.get_dict(SiteVisitAliases)
