"""URLs for the generated API views.

This module was generated by the ``generate_graph_views`` management command.
Do not edit by hand; re-run the command instead.

Include it from the project's urls.py:

    urlpatterns = [
        ...
        path("", include("bcap.urls_api_generated")),
    ]

These routes are what the drf_spectacular OpenAPI generator introspects.
"""

from django.urls import path

from bcap.views.generated import (
    ArchaeologicalSiteListView,
    ArchaeologicalSiteView,
    BcapMessageListView,
    BcapMessageView,
    ContributorListView,
    ContributorView,
    HcaPermitListView,
    HcaPermitView,
    LegislativeActListView,
    LegislativeActView,
    LgPersonListView,
    LgPersonView,
    LocalGovernmentListView,
    LocalGovernmentView,
    PermitApplicationListView,
    PermitApplicationView,
    ProcessRequirementListView,
    ProcessRequirementView,
    PublicationListView,
    PublicationView,
    SiteSubmissionListView,
    SiteSubmissionView,
    SiteVisitListView,
    SiteVisitView,
)

urlpatterns = [
    path(
        "api/archaeological_site",
        ArchaeologicalSiteListView.as_view(),
        name="api_archaeological_site_list",
    ),
    path(
        "api/archaeological_site/<uuid:pk>/",
        ArchaeologicalSiteView.as_view(),
        name="api_archaeological_site",
    ),
    path(
        "api/bcap_message",
        BcapMessageListView.as_view(),
        name="api_bcap_message_list",
    ),
    path(
        "api/bcap_message/<uuid:pk>/",
        BcapMessageView.as_view(),
        name="api_bcap_message",
    ),
    path(
        "api/contributor",
        ContributorListView.as_view(),
        name="api_contributor_list",
    ),
    path(
        "api/contributor/<uuid:pk>/",
        ContributorView.as_view(),
        name="api_contributor",
    ),
    path(
        "api/hca_permit",
        HcaPermitListView.as_view(),
        name="api_hca_permit_list",
    ),
    path(
        "api/hca_permit/<uuid:pk>/",
        HcaPermitView.as_view(),
        name="api_hca_permit",
    ),
    path(
        "api/legislative_act",
        LegislativeActListView.as_view(),
        name="api_legislative_act_list",
    ),
    path(
        "api/legislative_act/<uuid:pk>/",
        LegislativeActView.as_view(),
        name="api_legislative_act",
    ),
    path(
        "api/lg_person",
        LgPersonListView.as_view(),
        name="api_lg_person_list",
    ),
    path(
        "api/lg_person/<uuid:pk>/",
        LgPersonView.as_view(),
        name="api_lg_person",
    ),
    path(
        "api/local_government",
        LocalGovernmentListView.as_view(),
        name="api_local_government_list",
    ),
    path(
        "api/local_government/<uuid:pk>/",
        LocalGovernmentView.as_view(),
        name="api_local_government",
    ),
    path(
        "api/permit_application",
        PermitApplicationListView.as_view(),
        name="api_permit_application_list",
    ),
    path(
        "api/permit_application/<uuid:pk>/",
        PermitApplicationView.as_view(),
        name="api_permit_application",
    ),
    path(
        "api/process_requirement",
        ProcessRequirementListView.as_view(),
        name="api_process_requirement_list",
    ),
    path(
        "api/process_requirement/<uuid:pk>/",
        ProcessRequirementView.as_view(),
        name="api_process_requirement",
    ),
    path(
        "api/publication",
        PublicationListView.as_view(),
        name="api_publication_list",
    ),
    path(
        "api/publication/<uuid:pk>/",
        PublicationView.as_view(),
        name="api_publication",
    ),
    path(
        "api/site_submission",
        SiteSubmissionListView.as_view(),
        name="api_site_submission_list",
    ),
    path(
        "api/site_submission/<uuid:pk>/",
        SiteSubmissionView.as_view(),
        name="api_site_submission",
    ),
    path(
        "api/site_visit",
        SiteVisitListView.as_view(),
        name="api_site_visit_list",
    ),
    path(
        "api/site_visit/<uuid:pk>/",
        SiteVisitView.as_view(),
        name="api_site_visit",
    ),
]
