-- GENERATED by manage.py generate_databc_views - do not edit.

CREATE OR REPLACE VIEW publication.resource_flat AS SELECT * FROM publication.mv_resource_flat;

COMMENT ON VIEW publication.resource_flat IS
'Flat publication records, one row per resource. Cardinality-n values are delimiter-joined text (" | " between tiles, "; " within a tile).';
