-- GENERATED by manage.py generate_databc_views - do not edit.
-- Graph 3caf329f-b8f7-11e6-84a5-026d961c88e6
-- Requires 00_arches_util.sql to be applied first.
--
-- INVARIANTS:
--   * every key ALWAYS present; null, never absent.
--   * cardinality-n children are ALWAYS a jsonb array, [] when empty.
--   * cardinality-1 branches are an object, or null.
--   * array order is tiles.sortorder, then tileid.

SET client_min_messages = warning;
SET maintenance_work_mem = '512MB';
SET work_mem             = '128MB';

CREATE SCHEMA IF NOT EXISTS publication;

-- ---------------------------------------------------------------------
-- authors  (cardinality n)
-- ---------------------------------------------------------------------
DROP MATERIALIZED VIEW IF EXISTS publication.mv_authors CASCADE;
CREATE MATERIALIZED VIEW publication.mv_authors AS
WITH authors AS (
    SELECT t.resourceinstanceid AS resourceinstanceid,
           jsonb_agg(jsonb_build_object(
            'other_authors_unlisted', NULLIF(t.tiledata ->> '63f108ea-bdfb-11ed-a2b1-5254004d77d3', '')::boolean,
            'authors', arches_util.resource_ids(t.tiledata -> 'c03e8f18-bc30-11ed-bf42-5254004d77d3')
        ) ORDER BY COALESCE(t.sortorder, 2147483647), t.tileid) AS arr
    FROM public.tiles t
    WHERE t.nodegroupid = 'c03e8f18-bc30-11ed-bf42-5254004d77d3'::uuid
    GROUP BY t.resourceinstanceid
)
SELECT resourceinstanceid, arr AS authors FROM authors;

CREATE UNIQUE INDEX mv_authors_pk ON publication.mv_authors (resourceinstanceid);
