-- GENERATED by manage.py generate_databc_views - do not edit.
-- Graph 3caf329f-b8f7-11e6-84a5-026d961c88e6
-- Requires 00_arches_util.sql to be applied first.
--
-- INVARIANTS:
--   * every key ALWAYS present; null, never absent.
--   * cardinality-n children are ALWAYS a jsonb array, [] when empty.
--   * cardinality-1 branches are an object, or null.
--   * array order is tiles.sortorder, then tileid.

SET client_min_messages = warning;
SET maintenance_work_mem = '512MB';
SET work_mem             = '128MB';

CREATE SCHEMA IF NOT EXISTS publication;

-- ---------------------------------------------------------------------
-- copyright_type  (cardinality 1)
-- ---------------------------------------------------------------------
DROP MATERIALIZED VIEW IF EXISTS publication.mv_copyright_type CASCADE;
CREATE MATERIALIZED VIEW publication.mv_copyright_type AS
WITH copyright_type AS (
    SELECT DISTINCT ON (t.resourceinstanceid) t.resourceinstanceid AS resourceinstanceid,
           jsonb_build_object(
            'distribution_permitted', NULLIF(t.tiledata ->> 'a5f5cc8c-c40c-11ed-82cd-5254004d77d3', '')::boolean,
            'signed_agreement', arches_util.file_list(t.tiledata -> 'a5f5d268-c40c-11ed-82cd-5254004d77d3'),
            'agreement_text', arches_util.i18n_text(t.tiledata -> 'a5f5d6fa-c40c-11ed-82cd-5254004d77d3'),
            'copyright_type', arches_util.reference_flat(t.tiledata -> 'a5f5c7b4-c40c-11ed-82cd-5254004d77d3')
        ) AS obj
    FROM public.tiles t
    WHERE t.nodegroupid = 'a5f5c7b4-c40c-11ed-82cd-5254004d77d3'::uuid
    ORDER BY t.resourceinstanceid, COALESCE(t.sortorder, 2147483647), t.tileid
)
SELECT resourceinstanceid, obj AS copyright_type FROM copyright_type;

CREATE UNIQUE INDEX mv_copyright_type_pk ON publication.mv_copyright_type (resourceinstanceid);
