-- GENERATED by manage.py generate_databc_views - do not edit.
-- Graph 3caf329f-b8f7-11e6-84a5-026d961c88e6
-- Requires 00_arches_util.sql to be applied first.
--
-- INVARIANTS:
--   * every key ALWAYS present; null, never absent.
--   * cardinality-n children are ALWAYS a jsonb array, [] when empty.
--   * cardinality-1 branches are an object, or null.
--   * array order is tiles.sortorder, then tileid.

SET client_min_messages = warning;
SET maintenance_work_mem = '512MB';
SET work_mem             = '128MB';

CREATE SCHEMA IF NOT EXISTS publication;

-- ---------------------------------------------------------------------
-- information_carrier  (cardinality n)
-- ---------------------------------------------------------------------
DROP MATERIALIZED VIEW IF EXISTS publication.mv_information_carrier CASCADE;
CREATE MATERIALIZED VIEW publication.mv_information_carrier AS
WITH information_carrier AS (
    SELECT t.resourceinstanceid AS resourceinstanceid,
           jsonb_agg(jsonb_build_object(
            'information_carrier', arches_util.file_list(t.tiledata -> '9f210d2d-e74a-11e6-84a6-026d961c88e6')
        ) ORDER BY COALESCE(t.sortorder, 2147483647), t.tileid) AS arr
    FROM public.tiles t
    WHERE t.nodegroupid = '9f210d2d-e74a-11e6-84a6-026d961c88e6'::uuid
    GROUP BY t.resourceinstanceid
)
SELECT resourceinstanceid, arr AS information_carrier FROM information_carrier;

CREATE UNIQUE INDEX mv_information_carrier_pk ON publication.mv_information_carrier (resourceinstanceid);
