-- GENERATED by manage.py generate_databc_views - do not edit.
-- Graph 3caf329f-b8f7-11e6-84a5-026d961c88e6
-- Requires 00_arches_util.sql to be applied first.
--
-- INVARIANTS:
--   * every key ALWAYS present; null, never absent.
--   * cardinality-n children are ALWAYS a jsonb array, [] when empty.
--   * cardinality-1 branches are an object, or null.
--   * array order is tiles.sortorder, then tileid.

SET client_min_messages = warning;
SET maintenance_work_mem = '512MB';
SET work_mem             = '128MB';

CREATE SCHEMA IF NOT EXISTS publication;

-- ---------------------------------------------------------------------
-- keyword  (cardinality n)
-- ---------------------------------------------------------------------
DROP MATERIALIZED VIEW IF EXISTS publication.mv_keyword CASCADE;
CREATE MATERIALIZED VIEW publication.mv_keyword AS
WITH keyword AS (
    SELECT t.resourceinstanceid AS resourceinstanceid,
           jsonb_agg(jsonb_build_object(
            'keyword', arches_util.reference_flat(t.tiledata -> 'b5f5b1ed-e74a-11e6-84a6-026d961c88e6')
        ) ORDER BY COALESCE(t.sortorder, 2147483647), t.tileid) AS arr
    FROM public.tiles t
    WHERE t.nodegroupid = 'b5f5b1ed-e74a-11e6-84a6-026d961c88e6'::uuid
    GROUP BY t.resourceinstanceid
)
SELECT resourceinstanceid, arr AS keyword FROM keyword;

CREATE UNIQUE INDEX mv_keyword_pk ON publication.mv_keyword (resourceinstanceid);
