-- GENERATED by manage.py generate_databc_views - do not edit.

CREATE OR REPLACE PROCEDURE publication.refresh_resource(concurrent boolean DEFAULT true)
LANGUAGE plpgsql AS $$
DECLARE
    mode text := CASE WHEN concurrent THEN 'CONCURRENTLY' ELSE '' END;
    mv   text;
BEGIN
    FOREACH mv IN ARRAY ARRAY[
        'publication.mv_reference_link',
        'publication.mv_information_carrier',
        'publication.mv_copyright_type',
        'publication.mv_keyword',
        'publication.mv_authors',
        'publication.mv_publication_details',
        'publication.mv_resource'
    ]
    LOOP
        RAISE NOTICE 'refreshing %', mv;
        EXECUTE format('REFRESH MATERIALIZED VIEW %s %s', mode, mv);
        COMMIT;
    END LOOP;
END $$;
