-- GENERATED by manage.py generate_databc_views - do not edit.

CREATE OR REPLACE VIEW publication.resource AS SELECT * FROM publication.mv_resource;

COMMENT ON VIEW publication.resource IS
'Stable read contract for publication. One row per resource instance. Backed by mv_resource.';

-- GRANT SELECT ON publication.resource TO <app_role>;
