import { defineConfig } from "orval";

// Zod-only generation: the fetch layer is hand-written in components/pages/api.ts,
// so we emit just Zod schemas (runtime validation + z.infer types), one file per
// spec tag. Run via `npm run openapi:gen`.
const header = () => [
    "Generated by orval from the OpenAPI spec in schema.yml -- do not edit by hand.",
    "Regenerate with `npm run openapi:gen` (or `npm run api:gen` to also rebuild schema.yml).",
];

export default defineConfig({
    bcapZod: {
        input: { target: "schema.yml" },
        output: {
            mode: "tags",
            client: "zod",
            target: "bcap/src/bcap/client/zod",
            fileExtension: ".zod.ts",
            clean: ["bcap/src/bcap/client/zod"],
            override: { header },
        },
    },
});
