// This file is auto-generated by @hey-api/openapi-ts
//
// Generated from the OpenAPI spec in schema.yml.
// Route-bound schemas are named z<Operation><Role> -- e.g. zApiDashboardRetrieveResponse:
//   Role   = Response | Query | Body | Path
//   Method = verb in <Operation>: Retrieve/List=GET, Create=POST,
//            Update=PUT, PartialUpdate=PATCH, Destroy=DELETE
// Look up <Operation> in schema.yml `paths` for the url.
// Names without an Api* prefix (e.g. zDashboardCard) are shared, route-agnostic components.

import * as z from 'zod';

export const zDashboardCard = z.object({
    id: z.string(),
    requirement_name: z.string().optional(),
    requirement_due_date: z.string().optional(),
    project_name: z.string().optional(),
    application_number: z.string().optional(),
    industrial_sector: z.string().optional(),
    permit_id: z.string().nullish(),
    permit_number: z.string().optional(),
    permit_holder: z.string().optional(),
    permit_holder_ids: z.array(z.string()).optional(),
    project_officer: z.string().optional(),
    project_officer_id: z.string().nullish(),
    assessment_notes: z.string().optional(),
    ministry_assignee_name: z.string().optional(),
    ministry_assignee_id: z.string().nullish(),
    ministry_assignee_change_date: z.string().optional(),
    requirement_id: z.string().optional(),
    urgency: z.int().optional(),
    priority_level: z.string().optional(),
});

/**
 * One page of dashboard cards for the current user.
 *
 * `count` is the total number of cards matching the query across all pages;
 * `page` and `limit` echo the requested page number and page size; `results`
 * holds the cards for this page (at most `limit` of them). Each card's fields
 * are documented on the DashboardCard dataclass (as field help_text), so the
 * per-field descriptions surface in the generated OpenAPI spec.
 */
export const zDashboardPage = z.object({
    count: z.int().optional(),
    page: z.int().optional(),
    limit: z.int().optional(),
    results: z.array(zDashboardCard).optional(),
});

/**
 * The {node_value, display_value, details} object node value fields emit when as_representation is True.
 *
 * Mirrors the dict built in arches_querysets TileTree.get_value_with_context;
 * keep in sync if that shape changes upstream (unit test covers this).
 */
export const zNodeValueEnvelope = z.object({
    node_value: z.unknown(),
    display_value: z.string().readonly(),
    details: z.array(z.record(z.string(), z.unknown())).readonly(),
});

export const zProcessRequirementIsTemplateRequirementAliasedData = z.object({
    has_submission_requirement: zNodeValueEnvelope.nullable(),
    is_internal_requirement: zNodeValueEnvelope.nullable(),
    default_target_processing_time: zNodeValueEnvelope.nullish(),
    is_template_requirement: zNodeValueEnvelope.nullable(),
});

export const zProcessRequirementIsTemplateRequirementTile = z.object({
    tileid: z.uuid().nullish(),
    resourceinstance: z.uuid().nullish(),
    nodegroup: z.uuid().nullish(),
    parenttile: z.uuid().nullish(),
    aliased_data:
        zProcessRequirementIsTemplateRequirementAliasedData.optional(),
    sortorder: z.int().gte(-2147483648).lte(2147483647).nullish(),
    provisionaledits: z.unknown().optional(),
});

export const zProcessRequirementRequirementExecutionDurationAliasedData =
    z.object({
        requirement_process_start_date: zNodeValueEnvelope.nullish(),
        requirement_process_due_date: zNodeValueEnvelope.nullish(),
        requirement_process_completion_date: zNodeValueEnvelope.nullish(),
    });

export const zProcessRequirementRequirementExecutionDurationTile = z.object({
    tileid: z.uuid().nullish(),
    resourceinstance: z.uuid().nullish(),
    nodegroup: z.uuid().nullish(),
    parenttile: z.uuid().nullish(),
    aliased_data:
        zProcessRequirementRequirementExecutionDurationAliasedData.optional(),
    sortorder: z.int().gte(-2147483648).lte(2147483647).nullish(),
    provisionaledits: z.unknown().optional(),
});

export const zProcessRequirementRequirementIdentificationAliasedData = z.object(
    {
        requirement_identification: zNodeValueEnvelope.nullable(),
        requirement_name: zNodeValueEnvelope.nullable(),
        is_template_requirement:
            zProcessRequirementIsTemplateRequirementTile.nullish(),
    },
);

export const zProcessRequirementRequirementIdentificationTile = z.object({
    tileid: z.uuid().nullish(),
    resourceinstance: z.uuid().nullish(),
    nodegroup: z.uuid().nullish(),
    parenttile: z.uuid().nullish(),
    aliased_data:
        zProcessRequirementRequirementIdentificationAliasedData.optional(),
    sortorder: z.int().gte(-2147483648).lte(2147483647).nullish(),
    provisionaledits: z.unknown().optional(),
});

export const zProcessRequirementRequirmentSubmissionAliasedData = z.object({
    requirment_submission: zNodeValueEnvelope.nullish(),
});

export const zProcessRequirementRequirmentSubmissionTile = z.object({
    tileid: z.uuid().nullish(),
    resourceinstance: z.uuid().nullish(),
    nodegroup: z.uuid().nullish(),
    parenttile: z.uuid().nullish(),
    aliased_data: zProcessRequirementRequirmentSubmissionAliasedData.optional(),
    sortorder: z.int().gte(-2147483648).lte(2147483647).nullish(),
    provisionaledits: z.unknown().optional(),
});

export const zProcessRequirementSubRequirementAliasedData = z.object({
    sub_requirement_assessment_notes: zNodeValueEnvelope.nullish(),
    sub_requirement_description: zNodeValueEnvelope.nullish(),
    sub_requirement_mandatory: zNodeValueEnvelope.nullish(),
    sub_requirement_reference: zNodeValueEnvelope.nullish(),
    sub_requirement_satisfied: zNodeValueEnvelope.nullish(),
    sub_requirement_sort_order: zNodeValueEnvelope.nullable(),
    sub_requirement_name: zNodeValueEnvelope.nullable(),
});

export const zProcessRequirementSubRequirementAssessmentN1AliasedData =
    z.object({
        requirement_status: zNodeValueEnvelope.nullish(),
        assessment_notes: zNodeValueEnvelope.nullish(),
    });

export const zProcessRequirementSubRequirementAssessmentN1Tile = z.object({
    tileid: z.uuid().nullish(),
    resourceinstance: z.uuid().nullish(),
    nodegroup: z.uuid().nullish(),
    parenttile: z.uuid().nullish(),
    aliased_data:
        zProcessRequirementSubRequirementAssessmentN1AliasedData.optional(),
    sortorder: z.int().gte(-2147483648).lte(2147483647).nullish(),
    provisionaledits: z.unknown().optional(),
});

export const zProcessRequirementSubRequirementTile = z.object({
    tileid: z.uuid().nullish(),
    resourceinstance: z.uuid().nullish(),
    nodegroup: z.uuid().nullish(),
    parenttile: z.uuid().nullish(),
    aliased_data: zProcessRequirementSubRequirementAliasedData.optional(),
    sortorder: z.int().gte(-2147483648).lte(2147483647).nullish(),
    provisionaledits: z.unknown().optional(),
});

export const zResourceAliasedData = z.object({
    requirement_identification:
        zProcessRequirementRequirementIdentificationTile.nullish(),
    requirement_execution_duration:
        zProcessRequirementRequirementExecutionDurationTile.nullish(),
    requirment_submission:
        zProcessRequirementRequirmentSubmissionTile.nullish(),
    sub_requirement_assessment_n1:
        zProcessRequirementSubRequirementAssessmentN1Tile.nullish(),
    sub_requirement: z.array(zProcessRequirementSubRequirementTile).nullish(),
});

export const zPatchedProcessRequirement = z.object({
    resourceinstanceid: z.uuid().nullish(),
    aliased_data: zResourceAliasedData.optional(),
    graph_has_different_publication: z.boolean().readonly().optional(),
    name: z.unknown().optional(),
    descriptors: z.unknown().optional(),
    legacyid: z.string().readonly().nullish(),
    createdtime: z.iso.datetime().readonly().optional(),
    graph: z.uuid().nullish(),
    graph_publication: z.uuid().readonly().nullish(),
    resource_instance_lifecycle_state: z.uuid().readonly().optional(),
    principaluser: z.int().readonly().nullish(),
});

export const zProcessRequirement = z.object({
    resourceinstanceid: z.uuid().nullish(),
    aliased_data: zResourceAliasedData.optional(),
    graph_has_different_publication: z.boolean().readonly(),
    name: z.unknown(),
    descriptors: z.unknown(),
    legacyid: z.string().readonly().nullable(),
    createdtime: z.iso.datetime().readonly(),
    graph: z.uuid().nullish(),
    graph_publication: z.uuid().readonly().nullable(),
    resource_instance_lifecycle_state: z.uuid().readonly(),
    principaluser: z.int().readonly().nullable(),
});

export const zUserProfileResponse = z.object({
    username: z.string(),
    first_name: z.string(),
    last_name: z.string(),
    groups: z.array(z.string()).readonly(),
    contributor_id: z.string().readonly().nullable(),
});

/**
 * The {node_value, display_value, details} object node value fields emit when as_representation is True.
 *
 * Mirrors the dict built in arches_querysets TileTree.get_value_with_context;
 * keep in sync if that shape changes upstream (unit test covers this).
 */
export const zNodeValueEnvelopeWritable = z.object({
    node_value: z.unknown(),
});

export const zProcessRequirementIsTemplateRequirementAliasedDataWritable =
    z.object({
        has_submission_requirement: zNodeValueEnvelopeWritable.nullable(),
        is_internal_requirement: zNodeValueEnvelopeWritable.nullable(),
        default_target_processing_time: zNodeValueEnvelopeWritable.nullish(),
        is_template_requirement: zNodeValueEnvelopeWritable.nullable(),
    });

export const zProcessRequirementIsTemplateRequirementTileWritable = z.object({
    tileid: z.uuid().nullish(),
    resourceinstance: z.uuid().nullish(),
    nodegroup: z.uuid().nullish(),
    parenttile: z.uuid().nullish(),
    aliased_data:
        zProcessRequirementIsTemplateRequirementAliasedDataWritable.optional(),
    sortorder: z.int().gte(-2147483648).lte(2147483647).nullish(),
    provisionaledits: z.unknown().optional(),
});

export const zProcessRequirementRequirementExecutionDurationAliasedDataWritable =
    z.object({
        requirement_process_start_date: zNodeValueEnvelopeWritable.nullish(),
        requirement_process_due_date: zNodeValueEnvelopeWritable.nullish(),
        requirement_process_completion_date:
            zNodeValueEnvelopeWritable.nullish(),
    });

export const zProcessRequirementRequirementExecutionDurationTileWritable =
    z.object({
        tileid: z.uuid().nullish(),
        resourceinstance: z.uuid().nullish(),
        nodegroup: z.uuid().nullish(),
        parenttile: z.uuid().nullish(),
        aliased_data:
            zProcessRequirementRequirementExecutionDurationAliasedDataWritable.optional(),
        sortorder: z.int().gte(-2147483648).lte(2147483647).nullish(),
        provisionaledits: z.unknown().optional(),
    });

export const zProcessRequirementRequirementIdentificationAliasedDataWritable =
    z.object({
        requirement_identification: zNodeValueEnvelopeWritable.nullable(),
        requirement_name: zNodeValueEnvelopeWritable.nullable(),
        is_template_requirement:
            zProcessRequirementIsTemplateRequirementTileWritable.nullish(),
    });

export const zProcessRequirementRequirementIdentificationTileWritable =
    z.object({
        tileid: z.uuid().nullish(),
        resourceinstance: z.uuid().nullish(),
        nodegroup: z.uuid().nullish(),
        parenttile: z.uuid().nullish(),
        aliased_data:
            zProcessRequirementRequirementIdentificationAliasedDataWritable.optional(),
        sortorder: z.int().gte(-2147483648).lte(2147483647).nullish(),
        provisionaledits: z.unknown().optional(),
    });

export const zProcessRequirementRequirmentSubmissionAliasedDataWritable =
    z.object({
        requirment_submission: zNodeValueEnvelopeWritable.nullish(),
    });

export const zProcessRequirementRequirmentSubmissionTileWritable = z.object({
    tileid: z.uuid().nullish(),
    resourceinstance: z.uuid().nullish(),
    nodegroup: z.uuid().nullish(),
    parenttile: z.uuid().nullish(),
    aliased_data:
        zProcessRequirementRequirmentSubmissionAliasedDataWritable.optional(),
    sortorder: z.int().gte(-2147483648).lte(2147483647).nullish(),
    provisionaledits: z.unknown().optional(),
});

export const zProcessRequirementSubRequirementAliasedDataWritable = z.object({
    sub_requirement_assessment_notes: zNodeValueEnvelopeWritable.nullish(),
    sub_requirement_description: zNodeValueEnvelopeWritable.nullish(),
    sub_requirement_mandatory: zNodeValueEnvelopeWritable.nullish(),
    sub_requirement_reference: zNodeValueEnvelopeWritable.nullish(),
    sub_requirement_satisfied: zNodeValueEnvelopeWritable.nullish(),
    sub_requirement_sort_order: zNodeValueEnvelopeWritable.nullable(),
    sub_requirement_name: zNodeValueEnvelopeWritable.nullable(),
});

export const zProcessRequirementSubRequirementAssessmentN1AliasedDataWritable =
    z.object({
        requirement_status: zNodeValueEnvelopeWritable.nullish(),
        assessment_notes: zNodeValueEnvelopeWritable.nullish(),
    });

export const zProcessRequirementSubRequirementAssessmentN1TileWritable =
    z.object({
        tileid: z.uuid().nullish(),
        resourceinstance: z.uuid().nullish(),
        nodegroup: z.uuid().nullish(),
        parenttile: z.uuid().nullish(),
        aliased_data:
            zProcessRequirementSubRequirementAssessmentN1AliasedDataWritable.optional(),
        sortorder: z.int().gte(-2147483648).lte(2147483647).nullish(),
        provisionaledits: z.unknown().optional(),
    });

export const zProcessRequirementSubRequirementTileWritable = z.object({
    tileid: z.uuid().nullish(),
    resourceinstance: z.uuid().nullish(),
    nodegroup: z.uuid().nullish(),
    parenttile: z.uuid().nullish(),
    aliased_data:
        zProcessRequirementSubRequirementAliasedDataWritable.optional(),
    sortorder: z.int().gte(-2147483648).lte(2147483647).nullish(),
    provisionaledits: z.unknown().optional(),
});

export const zResourceAliasedDataWritable = z.object({
    requirement_identification:
        zProcessRequirementRequirementIdentificationTileWritable.nullish(),
    requirement_execution_duration:
        zProcessRequirementRequirementExecutionDurationTileWritable.nullish(),
    requirment_submission:
        zProcessRequirementRequirmentSubmissionTileWritable.nullish(),
    sub_requirement_assessment_n1:
        zProcessRequirementSubRequirementAssessmentN1TileWritable.nullish(),
    sub_requirement: z
        .array(zProcessRequirementSubRequirementTileWritable)
        .nullish(),
});

export const zPatchedProcessRequirementWritable = z.object({
    resourceinstanceid: z.uuid().nullish(),
    aliased_data: zResourceAliasedDataWritable.optional(),
    graph: z.uuid().nullish(),
});

export const zProcessRequirementWritable = z.object({
    resourceinstanceid: z.uuid().nullish(),
    aliased_data: zResourceAliasedDataWritable.optional(),
    graph: z.uuid().nullish(),
});

export const zUserProfileResponseWritable = z.object({
    username: z.string(),
    first_name: z.string(),
    last_name: z.string(),
});

export const zApiDashboardRetrieveQuery = z.object({
    contributor_id: z.string().min(1).nullish(),
    limit: z.int().gte(1).lte(100).optional(),
    order_by: z.string().min(1).nullish(),
    page: z.int().gte(1).optional(),
    status: z.enum(['UNASSIGNED']).nullish(),
});

export const zApiDashboardRetrieveResponse = zDashboardPage;

export const zApiResourceProcessRequirementDestroyPath = z.object({
    id: z.uuid(),
});

/**
 * No response body
 */
export const zApiResourceProcessRequirementDestroyResponse = z.void();

export const zApiResourceProcessRequirementRetrievePath = z.object({
    id: z.uuid(),
});

export const zApiResourceProcessRequirementRetrieveResponse =
    zProcessRequirement;

export const zApiResourceProcessRequirementPartialUpdateBody =
    zPatchedProcessRequirementWritable;

export const zApiResourceProcessRequirementPartialUpdatePath = z.object({
    id: z.uuid(),
});

export const zApiResourceProcessRequirementPartialUpdateResponse =
    zProcessRequirement;

export const zApiResourceProcessRequirementUpdateBody =
    zProcessRequirementWritable;

export const zApiResourceProcessRequirementUpdatePath = z.object({
    id: z.uuid(),
});

export const zApiResourceProcessRequirementUpdateResponse = zProcessRequirement;

export const zUserProfileRetrieveResponse = zUserProfileResponse;
