// This file is auto-generated by @hey-api/openapi-ts
//
// Generated from the OpenAPI spec in schema.yml.
// Route-bound schemas are named z<Operation><Role> -- e.g. zApiDashboardRetrieveResponse:
//   Role   = Response | Query | Body | Path
//   Method = verb in <Operation>: Retrieve/List=GET, Create=POST,
//            Update=PUT, PartialUpdate=PATCH, Destroy=DELETE
// Look up <Operation> in schema.yml `paths` for the url.
// Names without an Api* prefix (e.g. zDashboardCard) are shared, route-agnostic components.
//
// Field suffixes mirror the spec's `required` + `nullable`:
//   .nullable()  value may be null, but the field is still present
//   .optional()  field may be absent (undefined), but never null
//   .nullish()   both: null OR absent  (nullable + not required)
//
// zFoo vs zFooWritable: a component reused as BOTH a response and a
// request body splits in two when it has readOnly fields.
//   zFoo          response shape -- every field, incl. readOnly ones
//   zFooWritable  request-body shape -- readOnly fields dropped
//                 (e.g. display_value, details, name, descriptors)
// Parse responses with zFoo; build request bodies with zFooWritable.

import * as z from 'zod';

export const zBooleanAliasedNodeData = z.object({
    node_value: z.boolean().nullable(),
    display_value: z.string().readonly().optional(),
    details: z.array(z.record(z.string(), z.unknown())).readonly().optional(),
});

export const zDashboardCard = z.object({
    id: z.string(),
    requirement_name: z.string().optional(),
    requirement_due_date: z.string().optional(),
    project_name: z.string().optional(),
    application_number: z.string().optional(),
    industrial_sector: z.string().optional(),
    permit_id: z.string().nullish(),
    permit_number: z.string().optional(),
    permit_holder: z.string().optional(),
    permit_holder_ids: z.array(z.string()).optional(),
    project_officer: z.string().optional(),
    project_officer_id: z.string().nullish(),
    assessment_notes: z.string().optional(),
    ministry_assignee_name: z.string().optional(),
    ministry_assignee_id: z.string().nullish(),
    ministry_assignee_change_date: z.string().optional(),
    requirement_id: z.string().optional(),
    urgency: z.int().optional(),
    priority_level: z.string().optional(),
});

/**
 * One page of dashboard cards for the current user.
 *
 * `count` is the total number of cards matching the query across all pages;
 * `page` and `limit` echo the requested page number and page size; `results`
 * holds the cards for this page (at most `limit` of them). Each card's fields
 * are documented on the DashboardCard dataclass (as field help_text), so the
 * per-field descriptions surface in the generated OpenAPI spec.
 */
export const zDashboardPage = z.object({
    count: z.int().optional(),
    page: z.int().optional(),
    limit: z.int().optional(),
    results: z.array(zDashboardCard).optional(),
});

export const zDateAliasedNodeData = z.object({
    node_value: z.iso.datetime().nullable(),
    display_value: z.string().readonly().optional(),
    details: z.array(z.record(z.string(), z.unknown())).readonly().optional(),
});

export const zNumberAliasedNodeData = z.object({
    node_value: z.number().nullable(),
    display_value: z.string().readonly().optional(),
    details: z.array(z.record(z.string(), z.unknown())).readonly().optional(),
});

export const zProcessRequirementIsTemplateRequirementAliasedData = z.object({
    has_submission_requirement: zBooleanAliasedNodeData.nullable(),
    is_internal_requirement: zBooleanAliasedNodeData.nullable(),
    default_target_processing_time: zNumberAliasedNodeData.nullish(),
    is_template_requirement: zBooleanAliasedNodeData.nullable(),
});

export const zProcessRequirementIsTemplateRequirementTile = z.object({
    tileid: z.uuid().nullish(),
    resourceinstance: z.uuid().nullish(),
    nodegroup: z.uuid().nullish(),
    parenttile: z.uuid().nullish(),
    aliased_data:
        zProcessRequirementIsTemplateRequirementAliasedData.optional(),
    sortorder: z.int().gte(-2147483648).lte(2147483647).nullish(),
    provisionaledits: z
        .record(
            z.string(),
            z.object({
                value: z.record(z.string(), z.unknown()).optional(),
                status: z.string().optional(),
                action: z.string().optional(),
                reviewer: z.int().nullish(),
                timestamp: z.string().nullish(),
                reviewtimestamp: z.string().nullish(),
            }),
        )
        .nullish(),
});

export const zProcessRequirementRequirementExecutionDurationAliasedData =
    z.object({
        requirement_process_start_date: zDateAliasedNodeData.nullish(),
        requirement_process_due_date: zDateAliasedNodeData.nullish(),
        requirement_process_completion_date: zDateAliasedNodeData.nullish(),
    });

export const zProcessRequirementRequirementExecutionDurationTile = z.object({
    tileid: z.uuid().nullish(),
    resourceinstance: z.uuid().nullish(),
    nodegroup: z.uuid().nullish(),
    parenttile: z.uuid().nullish(),
    aliased_data:
        zProcessRequirementRequirementExecutionDurationAliasedData.optional(),
    sortorder: z.int().gte(-2147483648).lte(2147483647).nullish(),
    provisionaledits: z
        .record(
            z.string(),
            z.object({
                value: z.record(z.string(), z.unknown()).optional(),
                status: z.string().optional(),
                action: z.string().optional(),
                reviewer: z.int().nullish(),
                timestamp: z.string().nullish(),
                reviewtimestamp: z.string().nullish(),
            }),
        )
        .nullish(),
});

/**
 * One related resource summarized into a resource-instance node's `details`.
 */
export const zResourceInstanceDetail = z.object({
    resource_id: z.uuid().nullable(),
    display_value: z.string(),
});

export const zResourceInstanceAliasedNodeData = z.object({
    node_value: z
        .object({
            resourceId: z.uuid().optional(),
            ontologyProperty: z.string().nullish(),
            resourceXresourceId: z.string().nullish(),
            inverseOntologyProperty: z.string().nullish(),
        })
        .nullable(),
    display_value: z.string().readonly().optional(),
    details: z.array(zResourceInstanceDetail).readonly().optional(),
});

export const zProcessRequirementRequirmentSubmissionAliasedData = z.object({
    requirment_submission: zResourceInstanceAliasedNodeData.nullish(),
});

export const zProcessRequirementRequirmentSubmissionTile = z.object({
    tileid: z.uuid().nullish(),
    resourceinstance: z.uuid().nullish(),
    nodegroup: z.uuid().nullish(),
    parenttile: z.uuid().nullish(),
    aliased_data: zProcessRequirementRequirmentSubmissionAliasedData.optional(),
    sortorder: z.int().gte(-2147483648).lte(2147483647).nullish(),
    provisionaledits: z
        .record(
            z.string(),
            z.object({
                value: z.record(z.string(), z.unknown()).optional(),
                status: z.string().optional(),
                action: z.string().optional(),
                reviewer: z.int().nullish(),
                timestamp: z.string().nullish(),
                reviewtimestamp: z.string().nullish(),
            }),
        )
        .nullish(),
});

export const zStringAliasedNodeData = z.object({
    node_value: z
        .object({
            en: z
                .object({
                    value: z.string().nullish(),
                    direction: z.enum(['ltr', 'rtl']).optional(),
                })
                .optional(),
        })
        .nullable(),
    display_value: z.string().readonly().optional(),
    details: z.array(z.record(z.string(), z.unknown())).readonly().optional(),
});

export const zProcessRequirementRequirementIdentificationAliasedData = z.object(
    {
        requirement_identification: zStringAliasedNodeData.nullable(),
        requirement_name: zStringAliasedNodeData.nullable(),
        is_template_requirement:
            zProcessRequirementIsTemplateRequirementTile.nullish(),
    },
);

export const zProcessRequirementRequirementIdentificationTile = z.object({
    tileid: z.uuid().nullish(),
    resourceinstance: z.uuid().nullish(),
    nodegroup: z.uuid().nullish(),
    parenttile: z.uuid().nullish(),
    aliased_data:
        zProcessRequirementRequirementIdentificationAliasedData.optional(),
    sortorder: z.int().gte(-2147483648).lte(2147483647).nullish(),
    provisionaledits: z
        .record(
            z.string(),
            z.object({
                value: z.record(z.string(), z.unknown()).optional(),
                status: z.string().optional(),
                action: z.string().optional(),
                reviewer: z.int().nullish(),
                timestamp: z.string().nullish(),
                reviewtimestamp: z.string().nullish(),
            }),
        )
        .nullish(),
});

export const zProcessRequirementSubRequirementAliasedData = z.object({
    sub_requirement_assessment_notes: zStringAliasedNodeData.nullish(),
    sub_requirement_description: zStringAliasedNodeData.nullish(),
    sub_requirement_mandatory: zBooleanAliasedNodeData.nullish(),
    sub_requirement_reference: zResourceInstanceAliasedNodeData.nullish(),
    sub_requirement_satisfied: zBooleanAliasedNodeData.nullish(),
    sub_requirement_sort_order: zNumberAliasedNodeData.nullable(),
    sub_requirement_name: zStringAliasedNodeData.nullable(),
});

export const zProcessRequirementSubRequirementAssessmentN1AliasedData =
    z.object({
        requirement_status: zBooleanAliasedNodeData.nullish(),
        assessment_notes: zStringAliasedNodeData.nullish(),
    });

export const zProcessRequirementSubRequirementAssessmentN1Tile = z.object({
    tileid: z.uuid().nullish(),
    resourceinstance: z.uuid().nullish(),
    nodegroup: z.uuid().nullish(),
    parenttile: z.uuid().nullish(),
    aliased_data:
        zProcessRequirementSubRequirementAssessmentN1AliasedData.optional(),
    sortorder: z.int().gte(-2147483648).lte(2147483647).nullish(),
    provisionaledits: z
        .record(
            z.string(),
            z.object({
                value: z.record(z.string(), z.unknown()).optional(),
                status: z.string().optional(),
                action: z.string().optional(),
                reviewer: z.int().nullish(),
                timestamp: z.string().nullish(),
                reviewtimestamp: z.string().nullish(),
            }),
        )
        .nullish(),
});

export const zProcessRequirementSubRequirementTile = z.object({
    tileid: z.uuid().nullish(),
    resourceinstance: z.uuid().nullish(),
    nodegroup: z.uuid().nullish(),
    parenttile: z.uuid().nullish(),
    aliased_data: zProcessRequirementSubRequirementAliasedData.optional(),
    sortorder: z.int().gte(-2147483648).lte(2147483647).nullish(),
    provisionaledits: z
        .record(
            z.string(),
            z.object({
                value: z.record(z.string(), z.unknown()).optional(),
                status: z.string().optional(),
                action: z.string().optional(),
                reviewer: z.int().nullish(),
                timestamp: z.string().nullish(),
                reviewtimestamp: z.string().nullish(),
            }),
        )
        .nullish(),
});

export const zResourceAliasedData = z.object({
    requirement_identification:
        zProcessRequirementRequirementIdentificationTile.nullish(),
    requirement_execution_duration:
        zProcessRequirementRequirementExecutionDurationTile.nullish(),
    requirment_submission:
        zProcessRequirementRequirmentSubmissionTile.nullish(),
    sub_requirement_assessment_n1:
        zProcessRequirementSubRequirementAssessmentN1Tile.nullish(),
    sub_requirement: z.array(zProcessRequirementSubRequirementTile).nullish(),
});

export const zPatchedProcessRequirement = z.object({
    resourceinstanceid: z.uuid().nullish(),
    aliased_data: zResourceAliasedData.optional(),
    graph_has_different_publication: z.boolean().readonly().optional(),
    name: z.string().readonly().nullish(),
    descriptors: z
        .object({
            en: z
                .object({
                    name: z.string().optional(),
                    description: z.string().optional(),
                    map_popup: z.string().optional(),
                })
                .optional(),
        })
        .readonly()
        .nullish(),
    legacyid: z.string().readonly().nullish(),
    createdtime: z.iso.datetime().readonly().optional(),
    graph: z.uuid().nullish(),
    graph_publication: z.uuid().readonly().nullish(),
    resource_instance_lifecycle_state: z.uuid().readonly().optional(),
    principaluser: z.int().readonly().nullish(),
});

export const zProcessRequirement = z.object({
    resourceinstanceid: z.uuid().nullish(),
    aliased_data: zResourceAliasedData.optional(),
    graph_has_different_publication: z.boolean().readonly(),
    name: z.string().readonly().nullable(),
    descriptors: z
        .object({
            en: z
                .object({
                    name: z.string().optional(),
                    description: z.string().optional(),
                    map_popup: z.string().optional(),
                })
                .optional(),
        })
        .readonly()
        .nullable(),
    legacyid: z.string().readonly().nullable(),
    createdtime: z.iso.datetime().readonly(),
    graph: z.uuid().nullish(),
    graph_publication: z.uuid().readonly().nullable(),
    resource_instance_lifecycle_state: z.uuid().readonly(),
    principaluser: z.int().readonly().nullable(),
});

export const zUserProfileResponse = z.object({
    username: z.string(),
    first_name: z.string(),
    last_name: z.string(),
    groups: z.array(z.string()).readonly(),
});

export const zBooleanAliasedNodeDataWritable = z.object({
    node_value: z.boolean().nullable(),
});

export const zDateAliasedNodeDataWritable = z.object({
    node_value: z.iso.datetime().nullable(),
});

export const zNumberAliasedNodeDataWritable = z.object({
    node_value: z.number().nullable(),
});

export const zProcessRequirementIsTemplateRequirementAliasedDataWritable =
    z.object({
        has_submission_requirement: zBooleanAliasedNodeDataWritable.nullable(),
        is_internal_requirement: zBooleanAliasedNodeDataWritable.nullable(),
        default_target_processing_time:
            zNumberAliasedNodeDataWritable.nullish(),
        is_template_requirement: zBooleanAliasedNodeDataWritable.nullable(),
    });

export const zProcessRequirementIsTemplateRequirementTileWritable = z.object({
    tileid: z.uuid().nullish(),
    resourceinstance: z.uuid().nullish(),
    nodegroup: z.uuid().nullish(),
    parenttile: z.uuid().nullish(),
    aliased_data:
        zProcessRequirementIsTemplateRequirementAliasedDataWritable.optional(),
    sortorder: z.int().gte(-2147483648).lte(2147483647).nullish(),
    provisionaledits: z
        .record(
            z.string(),
            z.object({
                value: z.record(z.string(), z.unknown()).optional(),
                status: z.string().optional(),
                action: z.string().optional(),
                reviewer: z.int().nullish(),
                timestamp: z.string().nullish(),
                reviewtimestamp: z.string().nullish(),
            }),
        )
        .nullish(),
});

export const zProcessRequirementRequirementExecutionDurationAliasedDataWritable =
    z.object({
        requirement_process_start_date: zDateAliasedNodeDataWritable.nullish(),
        requirement_process_due_date: zDateAliasedNodeDataWritable.nullish(),
        requirement_process_completion_date:
            zDateAliasedNodeDataWritable.nullish(),
    });

export const zProcessRequirementRequirementExecutionDurationTileWritable =
    z.object({
        tileid: z.uuid().nullish(),
        resourceinstance: z.uuid().nullish(),
        nodegroup: z.uuid().nullish(),
        parenttile: z.uuid().nullish(),
        aliased_data:
            zProcessRequirementRequirementExecutionDurationAliasedDataWritable.optional(),
        sortorder: z.int().gte(-2147483648).lte(2147483647).nullish(),
        provisionaledits: z
            .record(
                z.string(),
                z.object({
                    value: z.record(z.string(), z.unknown()).optional(),
                    status: z.string().optional(),
                    action: z.string().optional(),
                    reviewer: z.int().nullish(),
                    timestamp: z.string().nullish(),
                    reviewtimestamp: z.string().nullish(),
                }),
            )
            .nullish(),
    });

export const zResourceInstanceAliasedNodeDataWritable = z.object({
    node_value: z
        .object({
            resourceId: z.uuid().optional(),
            ontologyProperty: z.string().nullish(),
            resourceXresourceId: z.string().nullish(),
            inverseOntologyProperty: z.string().nullish(),
        })
        .nullable(),
});

export const zProcessRequirementRequirmentSubmissionAliasedDataWritable =
    z.object({
        requirment_submission:
            zResourceInstanceAliasedNodeDataWritable.nullish(),
    });

export const zProcessRequirementRequirmentSubmissionTileWritable = z.object({
    tileid: z.uuid().nullish(),
    resourceinstance: z.uuid().nullish(),
    nodegroup: z.uuid().nullish(),
    parenttile: z.uuid().nullish(),
    aliased_data:
        zProcessRequirementRequirmentSubmissionAliasedDataWritable.optional(),
    sortorder: z.int().gte(-2147483648).lte(2147483647).nullish(),
    provisionaledits: z
        .record(
            z.string(),
            z.object({
                value: z.record(z.string(), z.unknown()).optional(),
                status: z.string().optional(),
                action: z.string().optional(),
                reviewer: z.int().nullish(),
                timestamp: z.string().nullish(),
                reviewtimestamp: z.string().nullish(),
            }),
        )
        .nullish(),
});

export const zStringAliasedNodeDataWritable = z.object({
    node_value: z
        .object({
            en: z
                .object({
                    value: z.string().nullish(),
                    direction: z.enum(['ltr', 'rtl']).optional(),
                })
                .optional(),
        })
        .nullable(),
});

export const zProcessRequirementRequirementIdentificationAliasedDataWritable =
    z.object({
        requirement_identification: zStringAliasedNodeDataWritable.nullable(),
        requirement_name: zStringAliasedNodeDataWritable.nullable(),
        is_template_requirement:
            zProcessRequirementIsTemplateRequirementTileWritable.nullish(),
    });

export const zProcessRequirementRequirementIdentificationTileWritable =
    z.object({
        tileid: z.uuid().nullish(),
        resourceinstance: z.uuid().nullish(),
        nodegroup: z.uuid().nullish(),
        parenttile: z.uuid().nullish(),
        aliased_data:
            zProcessRequirementRequirementIdentificationAliasedDataWritable.optional(),
        sortorder: z.int().gte(-2147483648).lte(2147483647).nullish(),
        provisionaledits: z
            .record(
                z.string(),
                z.object({
                    value: z.record(z.string(), z.unknown()).optional(),
                    status: z.string().optional(),
                    action: z.string().optional(),
                    reviewer: z.int().nullish(),
                    timestamp: z.string().nullish(),
                    reviewtimestamp: z.string().nullish(),
                }),
            )
            .nullish(),
    });

export const zProcessRequirementSubRequirementAliasedDataWritable = z.object({
    sub_requirement_assessment_notes: zStringAliasedNodeDataWritable.nullish(),
    sub_requirement_description: zStringAliasedNodeDataWritable.nullish(),
    sub_requirement_mandatory: zBooleanAliasedNodeDataWritable.nullish(),
    sub_requirement_reference:
        zResourceInstanceAliasedNodeDataWritable.nullish(),
    sub_requirement_satisfied: zBooleanAliasedNodeDataWritable.nullish(),
    sub_requirement_sort_order: zNumberAliasedNodeDataWritable.nullable(),
    sub_requirement_name: zStringAliasedNodeDataWritable.nullable(),
});

export const zProcessRequirementSubRequirementAssessmentN1AliasedDataWritable =
    z.object({
        requirement_status: zBooleanAliasedNodeDataWritable.nullish(),
        assessment_notes: zStringAliasedNodeDataWritable.nullish(),
    });

export const zProcessRequirementSubRequirementAssessmentN1TileWritable =
    z.object({
        tileid: z.uuid().nullish(),
        resourceinstance: z.uuid().nullish(),
        nodegroup: z.uuid().nullish(),
        parenttile: z.uuid().nullish(),
        aliased_data:
            zProcessRequirementSubRequirementAssessmentN1AliasedDataWritable.optional(),
        sortorder: z.int().gte(-2147483648).lte(2147483647).nullish(),
        provisionaledits: z
            .record(
                z.string(),
                z.object({
                    value: z.record(z.string(), z.unknown()).optional(),
                    status: z.string().optional(),
                    action: z.string().optional(),
                    reviewer: z.int().nullish(),
                    timestamp: z.string().nullish(),
                    reviewtimestamp: z.string().nullish(),
                }),
            )
            .nullish(),
    });

export const zProcessRequirementSubRequirementTileWritable = z.object({
    tileid: z.uuid().nullish(),
    resourceinstance: z.uuid().nullish(),
    nodegroup: z.uuid().nullish(),
    parenttile: z.uuid().nullish(),
    aliased_data:
        zProcessRequirementSubRequirementAliasedDataWritable.optional(),
    sortorder: z.int().gte(-2147483648).lte(2147483647).nullish(),
    provisionaledits: z
        .record(
            z.string(),
            z.object({
                value: z.record(z.string(), z.unknown()).optional(),
                status: z.string().optional(),
                action: z.string().optional(),
                reviewer: z.int().nullish(),
                timestamp: z.string().nullish(),
                reviewtimestamp: z.string().nullish(),
            }),
        )
        .nullish(),
});

export const zResourceAliasedDataWritable = z.object({
    requirement_identification:
        zProcessRequirementRequirementIdentificationTileWritable.nullish(),
    requirement_execution_duration:
        zProcessRequirementRequirementExecutionDurationTileWritable.nullish(),
    requirment_submission:
        zProcessRequirementRequirmentSubmissionTileWritable.nullish(),
    sub_requirement_assessment_n1:
        zProcessRequirementSubRequirementAssessmentN1TileWritable.nullish(),
    sub_requirement: z
        .array(zProcessRequirementSubRequirementTileWritable)
        .nullish(),
});

export const zPatchedProcessRequirementWritable = z.object({
    resourceinstanceid: z.uuid().nullish(),
    aliased_data: zResourceAliasedDataWritable.optional(),
    graph: z.uuid().nullish(),
});

export const zProcessRequirementWritable = z.object({
    resourceinstanceid: z.uuid().nullish(),
    aliased_data: zResourceAliasedDataWritable.optional(),
    graph: z.uuid().nullish(),
});

export const zUserProfileResponseWritable = z.object({
    username: z.string(),
    first_name: z.string(),
    last_name: z.string(),
});

export const zApiDashboardRetrieveQuery = z.object({
    contributor_id: z.string().min(1).nullish(),
    limit: z.int().gte(1).lte(100).optional(),
    order_by: z.string().min(1).nullish(),
    page: z.int().gte(1).optional(),
    status: z.enum(['UNASSIGNED']).nullish(),
});

export const zApiDashboardRetrieveResponse = zDashboardPage;

export const zApiResourceProcessRequirementDestroyPath = z.object({
    id: z.uuid(),
});

/**
 * No response body
 */
export const zApiResourceProcessRequirementDestroyResponse = z.void();

export const zApiResourceProcessRequirementRetrievePath = z.object({
    id: z.uuid(),
});

export const zApiResourceProcessRequirementRetrieveResponse =
    zProcessRequirement;

export const zApiResourceProcessRequirementPartialUpdateBody =
    zPatchedProcessRequirementWritable;

export const zApiResourceProcessRequirementPartialUpdatePath = z.object({
    id: z.uuid(),
});

export const zApiResourceProcessRequirementPartialUpdateResponse =
    zProcessRequirement;

export const zApiResourceProcessRequirementUpdateBody =
    zProcessRequirementWritable;

export const zApiResourceProcessRequirementUpdatePath = z.object({
    id: z.uuid(),
});

export const zApiResourceProcessRequirementUpdateResponse = zProcessRequirement;

export const zUserProfileRetrieveResponse = zUserProfileResponse;
