-- GENERATED by manage.py generate_databc_views - do not edit.

CREATE OR REPLACE VIEW site_visit.resource_flat AS SELECT * FROM site_visit.mv_resource_flat;
CREATE OR REPLACE VIEW site_visit.site_visit_location_flat AS SELECT * FROM site_visit.mv_site_visit_location_flat;

COMMENT ON VIEW site_visit.resource_flat IS
'Flat site_visit records, one row per resource. Cardinality-n values are delimiter-joined text (" | " between tiles, "; " within a tile).';
