-- GENERATED - edit sv_spec.py and re-run generate.py.
-- Requires site_visit/mv_resource_v1.sql to be applied first.
--
-- Built ON TOP OF mv_resource_v1: one source of truth, zero joins.
-- CONTRACT:
--   * cardinality-1 fields keep REAL TYPES (date, numeric, boolean, text)
--   * cardinality-n fields are TEXT CSV: ' | ' between tiles, '; ' within a tile
--   * POSITIONAL ALIGNMENT IS THE CONTRACT. Null elements emit an EMPTY SLOT.
--   * references come in pairs: x (labels) + x_ids

SET client_min_messages = warning;

DROP MATERIALIZED VIEW IF EXISTS site_visit.mv_resource_flat_v1 CASCADE;
CREATE MATERIALIZED VIEW site_visit.mv_resource_flat_v1 AS
SELECT
    r.resourceinstanceid,
    r.site_visit_location_geom,
    r.site_visit_location_geom_type,
    r.site_visit_location_source_valid,
    r.site_visit_location_points,
    r.site_visit_location_lines,
    r.site_visit_location_polygons,
    arches_util.deep_csv_nested(r.ancestral_remains, '{}'::text[], 'ancestral_remains_type', 'label', ' | ', '; ') AS ancestral_remains_type,
    arches_util.deep_csv_nested(r.ancestral_remains, '{}'::text[], 'ancestral_remains_type', 'list_item_id', ' | ', '; ') AS ancestral_remains_type_ids,
    arches_util.deep_csv(r.ancestral_remains, '{}'::text[], 'multiple_burials', ' | ') AS multiple_burials,
    arches_util.deep_csv_nested(r.ancestral_remains, '{}'::text[], 'ancestral_remains_status', 'label', ' | ', '; ') AS ancestral_remains_status,
    arches_util.deep_csv_nested(r.ancestral_remains, '{}'::text[], 'ancestral_remains_status', 'list_item_id', ' | ', '; ') AS ancestral_remains_status_ids,
    arches_util.deep_csv(r.ancestral_remains, '{}'::text[], 'ancestral_remains_remarks', ' | ') AS ancestral_remains_remarks,
    arches_util.deep_csv(r.ancestral_remains, '{}'::text[], 'minimum_number_of_individuals', ' | ') AS minimum_number_of_individuals,
    arches_util.deep_res_csv(r.ancestral_remains, '{}'::text[], 'ancestral_remains_repository', ' | ') AS ancestral_remains_repository,
    arches_util.deep_csv(r.ancestral_remains, '{}'::text[], 'ancestral_remains_repository', ' | ') AS ancestral_remains_repository_ids,
    jsonb_array_length(arches_util.as_array(r.ancestral_remains)) AS ancestral_remains_count,
    arches_util.resource_names_csv(r.site_visit_details -> 'site_form_authors', ' | ') AS site_form_authors,
    arches_util.a2csv(r.site_visit_details -> 'site_form_authors', NULL, ' | ') AS site_form_authors_ids,
    arches_util.a2csv(r.site_visit_details -> 'site_visit_type', 'label', ' | ') AS site_visit_type,
    arches_util.a2csv(r.site_visit_details -> 'site_visit_type', 'list_item_id', ' | ') AS site_visit_type_ids,
    (r.site_visit_details ->> 'is_site_visit_permitted')::boolean AS is_site_visit_permitted,
    (r.site_visit_details ->> 'first_date_of_site_visit')::date AS first_date_of_site_visit,
    (r.site_visit_details ->> 'last_date_of_site_visit')::date AS last_date_of_site_visit,
    r.site_visit_details ->> 'project_description' AS project_description,
    arches_util.resource_names_csv(r.site_visit_details -> 'associated_permit', ' | ') AS associated_permit,
    arches_util.a2csv(r.site_visit_details -> 'associated_permit', NULL, ' | ') AS associated_permit_ids,
    arches_util.resource_name(arches_util.to_uuid(r.site_visit_details ->> 'archaeological_site')) AS archaeological_site,
    r.site_visit_details ->> 'archaeological_site' AS archaeological_site_id,
    arches_util.resource_name(arches_util.to_uuid(r.site_visit_details ->> 'affiliation')) AS affiliation,
    r.site_visit_details ->> 'affiliation' AS affiliation_id,
    arches_util.deep_csv(r.related_documents -> 'related_site_documents', '{}'::text[], 'related_document_description', ' | ') AS related_document_description,
    arches_util.deep_csv_nested(r.related_documents -> 'related_site_documents', '{}'::text[], 'related_document_type', 'label', ' | ', '; ') AS related_document_type,
    arches_util.deep_csv_nested(r.related_documents -> 'related_site_documents', '{}'::text[], 'related_document_type', 'list_item_id', ' | ', '; ') AS related_document_type_ids,
    arches_util.deep_csv_nested(r.related_documents -> 'related_site_documents', '{}'::text[], 'related_site_documents', 'name', ' | ', '; ') AS related_site_documents,
    arches_util.deep_csv_nested(r.related_documents -> 'related_site_documents', '{}'::text[], 'related_site_documents', 'file_id', ' | ', '; ') AS related_site_documents_file_ids,
    jsonb_array_length(arches_util.as_array(r.related_documents -> 'related_site_documents')) AS related_site_documents_count,
    arches_util.deep_res_csv_nested(r.related_documents -> 'publication_reference', '{}'::text[], 'publication_reference', ' | ', '; ') AS publication_reference,
    arches_util.deep_csv_nested(r.related_documents -> 'publication_reference', '{}'::text[], 'publication_reference', NULL, ' | ', '; ') AS publication_reference_ids,
    jsonb_array_length(arches_util.as_array(r.related_documents -> 'publication_reference')) AS publication_reference_count,
    arches_util.deep_csv(r.related_documents -> 'site_images', '{}'::text[], 'primary_image', ' | ') AS primary_image,
    arches_util.deep_csv_nested(r.related_documents -> 'site_images', '{}'::text[], 'image_type', 'label', ' | ', '; ') AS image_type,
    arches_util.deep_csv_nested(r.related_documents -> 'site_images', '{}'::text[], 'image_type', 'list_item_id', ' | ', '; ') AS image_type_ids,
    arches_util.deep_csv_nested(r.related_documents -> 'site_images', '{}'::text[], 'site_images', 'name', ' | ', '; ') AS site_images,
    arches_util.deep_csv_nested(r.related_documents -> 'site_images', '{}'::text[], 'site_images', 'file_id', ' | ', '; ') AS site_images_file_ids,
    arches_util.deep_csv(r.related_documents -> 'site_images', '{}'::text[], 'photographer', ' | ') AS photographer,
    arches_util.deep_csv_nested(r.related_documents -> 'site_images', '{}'::text[], 'image_view', 'label', ' | ', '; ') AS image_view,
    arches_util.deep_csv_nested(r.related_documents -> 'site_images', '{}'::text[], 'image_view', 'list_item_id', ' | ', '; ') AS image_view_ids,
    arches_util.deep_csv(r.related_documents -> 'site_images', '{}'::text[], 'image_description', ' | ') AS image_description,
    arches_util.deep_csv(r.related_documents -> 'site_images', '{}'::text[], 'copyright', ' | ') AS copyright,
    arches_util.deep_csv(r.related_documents -> 'site_images', '{}'::text[], 'image_date', ' | ') AS image_date,
    arches_util.deep_csv(r.related_documents -> 'site_images', '{}'::text[], 'image_features', ' | ') AS image_features,
    jsonb_array_length(arches_util.as_array(r.related_documents -> 'site_images')) AS site_images_count,
    arches_util.deep_csv(r.remarks_and_recommendations -> 'recommendation', '{}'::text[], 'recorders_recommendation', ' | ') AS recorders_recommendation,
    arches_util.deep_csv(r.remarks_and_recommendations -> 'recommendation', '{}'::text[], 'archaeology_branch_recommendation', ' | ') AS archaeology_branch_recommendation,
    jsonb_array_length(arches_util.as_array(r.remarks_and_recommendations -> 'recommendation')) AS recommendation_count,
    arches_util.deep_csv_nested(r.remarks_and_recommendations -> 'general_remark', '{}'::text[], 'remark_source', 'label', ' | ', '; ') AS remark_source,
    arches_util.deep_csv_nested(r.remarks_and_recommendations -> 'general_remark', '{}'::text[], 'remark_source', 'list_item_id', ' | ', '; ') AS remark_source_ids,
    arches_util.deep_csv(r.remarks_and_recommendations -> 'general_remark', '{}'::text[], 'remark_date', ' | ') AS remark_date,
    arches_util.deep_csv(r.remarks_and_recommendations -> 'general_remark', '{}'::text[], 'remark', ' | ') AS remark,
    jsonb_array_length(arches_util.as_array(r.remarks_and_recommendations -> 'general_remark')) AS general_remark_count,
    r.identification -> 'temporary_number' ->> 'temporary_number' AS temporary_number,
    arches_util.resource_name(arches_util.to_uuid(r.identification -> 'temporary_number' ->> 'temporary_number_assigned_by')) AS temporary_number_assigned_by,
    r.identification -> 'temporary_number' ->> 'temporary_number_assigned_by' AS temporary_number_assigned_by_id,
    (r.identification -> 'temporary_number' ->> 'temporary_number_assigned_date')::date AS temporary_number_assigned_date,
    arches_util.deep_csv(r.identification -> 'new_site_names', '{}'::text[], 'name', ' | ') AS name,
    arches_util.deep_res_csv(r.identification -> 'new_site_names', '{}'::text[], 'assigned_or_reported_by', ' | ') AS assigned_or_reported_by,
    arches_util.deep_csv(r.identification -> 'new_site_names', '{}'::text[], 'assigned_or_reported_by', ' | ') AS assigned_or_reported_by_ids,
    arches_util.deep_csv_nested(r.identification -> 'new_site_names', '{}'::text[], 'name_type', 'label', ' | ', '; ') AS name_type,
    arches_util.deep_csv_nested(r.identification -> 'new_site_names', '{}'::text[], 'name_type', 'list_item_id', ' | ', '; ') AS name_type_ids,
    arches_util.deep_csv(r.identification -> 'new_site_names', '{}'::text[], 'name_remarks', ' | ') AS name_remarks,
    arches_util.deep_csv(r.identification -> 'new_site_names', '{}'::text[], 'assigned_or_reported_date', ' | ') AS assigned_or_reported_date,
    jsonb_array_length(arches_util.as_array(r.identification -> 'new_site_names')) AS new_site_names_count,
    arches_util.deep_csv(r.archaeological_data -> 'archaeological_culture', '{}'::text[], 'culture_remarks', ' | ') AS culture_remarks,
    arches_util.deep_csv_nested(r.archaeological_data -> 'archaeological_culture', '{}'::text[], 'archaeological_culture', 'label', ' | ', '; ') AS archaeological_culture,
    arches_util.deep_csv_nested(r.archaeological_data -> 'archaeological_culture', '{}'::text[], 'archaeological_culture', 'list_item_id', ' | ', '; ') AS archaeological_culture_ids,
    jsonb_array_length(arches_util.as_array(r.archaeological_data -> 'archaeological_culture')) AS archaeological_culture_count,
    arches_util.deep_csv(r.archaeological_data -> 'stratigraphy', '{}'::text[], 'stratigraphy', ' | ') AS stratigraphy,
    jsonb_array_length(arches_util.as_array(r.archaeological_data -> 'stratigraphy')) AS stratigraphy_count,
    arches_util.deep_csv_nested(r.archaeological_data -> 'additional_site_typology', '{}'::text[], 'typology_class', 'label', ' | ', '; ') AS typology_class,
    arches_util.deep_csv_nested(r.archaeological_data -> 'additional_site_typology', '{}'::text[], 'typology_class', 'list_item_id', ' | ', '; ') AS typology_class_ids,
    arches_util.deep_csv(r.archaeological_data -> 'additional_site_typology', '{}'::text[], 'typology_remark', ' | ') AS typology_remark,
    jsonb_array_length(arches_util.as_array(r.archaeological_data -> 'additional_site_typology')) AS additional_site_typology_count,
    arches_util.deep_csv_nested(r.archaeological_data -> 'site_disturbance', '{}'::text[], 'disturbance_period', 'label', ' | ', '; ') AS disturbance_period,
    arches_util.deep_csv_nested(r.archaeological_data -> 'site_disturbance', '{}'::text[], 'disturbance_period', 'list_item_id', ' | ', '; ') AS disturbance_period_ids,
    arches_util.deep_csv_nested(r.archaeological_data -> 'site_disturbance', '{}'::text[], 'disturbance_cause', 'label', ' | ', '; ') AS disturbance_cause,
    arches_util.deep_csv_nested(r.archaeological_data -> 'site_disturbance', '{}'::text[], 'disturbance_cause', 'list_item_id', ' | ', '; ') AS disturbance_cause_ids,
    arches_util.deep_csv(r.archaeological_data -> 'site_disturbance', '{}'::text[], 'disturbance_remarks', ' | ') AS disturbance_remarks,
    jsonb_array_length(arches_util.as_array(r.archaeological_data -> 'site_disturbance')) AS site_disturbance_count,
    arches_util.deep_csv_nested(r.archaeological_data -> 'chronology', '{}'::text[], 'end_year_qualifier', 'label', ' | ', '; ') AS end_year_qualifier,
    arches_util.deep_csv_nested(r.archaeological_data -> 'chronology', '{}'::text[], 'end_year_qualifier', 'list_item_id', ' | ', '; ') AS end_year_qualifier_ids,
    arches_util.deep_csv_nested(r.archaeological_data -> 'chronology', '{}'::text[], 'end_year_calendar', 'label', ' | ', '; ') AS end_year_calendar,
    arches_util.deep_csv_nested(r.archaeological_data -> 'chronology', '{}'::text[], 'end_year_calendar', 'list_item_id', ' | ', '; ') AS end_year_calendar_ids,
    arches_util.deep_csv(r.archaeological_data -> 'chronology', '{}'::text[], 'chronology_remarks', ' | ') AS chronology_remarks,
    arches_util.deep_csv_nested(r.archaeological_data -> 'chronology', '{}'::text[], 'determination_method', 'label', ' | ', '; ') AS determination_method,
    arches_util.deep_csv_nested(r.archaeological_data -> 'chronology', '{}'::text[], 'determination_method', 'list_item_id', ' | ', '; ') AS determination_method_ids,
    arches_util.deep_csv(r.archaeological_data -> 'chronology', '{}'::text[], 'start_year', ' | ') AS start_year,
    arches_util.deep_csv(r.archaeological_data -> 'chronology', '{}'::text[], 'information_source', ' | ') AS information_source,
    arches_util.deep_csv(r.archaeological_data -> 'chronology', '{}'::text[], 'end_year', ' | ') AS end_year,
    arches_util.deep_csv_nested(r.archaeological_data -> 'chronology', '{}'::text[], 'start_year_calendar', 'label', ' | ', '; ') AS start_year_calendar,
    arches_util.deep_csv_nested(r.archaeological_data -> 'chronology', '{}'::text[], 'start_year_calendar', 'list_item_id', ' | ', '; ') AS start_year_calendar_ids,
    arches_util.deep_csv_nested(r.archaeological_data -> 'chronology', '{}'::text[], 'start_year_qualifier', 'label', ' | ', '; ') AS start_year_qualifier,
    arches_util.deep_csv_nested(r.archaeological_data -> 'chronology', '{}'::text[], 'start_year_qualifier', 'list_item_id', ' | ', '; ') AS start_year_qualifier_ids,
    jsonb_array_length(arches_util.as_array(r.archaeological_data -> 'chronology')) AS chronology_count,
    arches_util.deep_csv_nested(r.archaeological_data -> 'cultural_material', '{}'::text[], 'cultural_material_type', 'label', ' | ', '; ') AS cultural_material_type,
    arches_util.deep_csv_nested(r.archaeological_data -> 'cultural_material', '{}'::text[], 'cultural_material_type', 'list_item_id', ' | ', '; ') AS cultural_material_type_ids,
    arches_util.deep_csv_nested(r.archaeological_data -> 'cultural_material', '{}'::text[], 'cultural_material_status', 'label', ' | ', '; ') AS cultural_material_status,
    arches_util.deep_csv_nested(r.archaeological_data -> 'cultural_material', '{}'::text[], 'cultural_material_status', 'list_item_id', ' | ', '; ') AS cultural_material_status_ids,
    arches_util.deep_csv(r.archaeological_data -> 'cultural_material', '{}'::text[], 'cultural_material_details', ' | ') AS cultural_material_details,
    arches_util.deep_csv(r.archaeological_data -> 'cultural_material', '{}'::text[], 'number_of_artifacts', ' | ') AS number_of_artifacts,
    arches_util.deep_res_csv(r.archaeological_data -> 'cultural_material', '{}'::text[], 'repository', ' | ') AS repository,
    arches_util.deep_csv(r.archaeological_data -> 'cultural_material', '{}'::text[], 'repository', ' | ') AS repository_ids,
    jsonb_array_length(arches_util.as_array(r.archaeological_data -> 'cultural_material')) AS cultural_material_count,
    arches_util.deep_csv(r.archaeological_data -> 'archaeological_feature', '{}'::text[], 'feature_count', ' | ') AS feature_count,
    arches_util.deep_csv_nested(r.archaeological_data -> 'archaeological_feature', '{}'::text[], 'archaeological_feature', 'label', ' | ', '; ') AS archaeological_feature,
    arches_util.deep_csv_nested(r.archaeological_data -> 'archaeological_feature', '{}'::text[], 'archaeological_feature', 'list_item_id', ' | ', '; ') AS archaeological_feature_ids,
    arches_util.deep_csv(r.archaeological_data -> 'archaeological_feature', '{}'::text[], 'feature_remarks', ' | ') AS feature_remarks,
    jsonb_array_length(arches_util.as_array(r.archaeological_data -> 'archaeological_feature')) AS archaeological_feature_count,
    arches_util.deep_csv(r.site_visit_details -> 'site_visit_team' -> 'team_member', '{}'::text[], 'was_on_site', ' | ') AS was_on_site,
    arches_util.deep_res_csv(r.site_visit_details -> 'site_visit_team' -> 'team_member', '{}'::text[], 'team_member', ' | ') AS team_member,
    arches_util.deep_csv(r.site_visit_details -> 'site_visit_team' -> 'team_member', '{}'::text[], 'team_member', ' | ') AS team_member_ids,
    arches_util.deep_csv_nested(r.site_visit_details -> 'site_visit_team' -> 'team_member', '{}'::text[], 'member_roles', 'label', ' | ', '; ') AS member_roles,
    arches_util.deep_csv_nested(r.site_visit_details -> 'site_visit_team' -> 'team_member', '{}'::text[], 'member_roles', 'list_item_id', ' | ', '; ') AS member_roles_ids,
    jsonb_array_length(arches_util.as_array(r.site_visit_details -> 'site_visit_team' -> 'team_member')) AS team_member_count
FROM site_visit.mv_resource_v1 r;

CREATE UNIQUE INDEX mv_resource_flat_v1_pk ON site_visit.mv_resource_flat_v1 (resourceinstanceid);
CREATE INDEX mv_resource_flat_v1_site_visit_location_gix ON site_visit.mv_resource_flat_v1 USING GIST (site_visit_location_geom);
