-- GENERATED by manage.py generate_databc_views - do not edit.

CREATE OR REPLACE PROCEDURE site_visit.refresh_resource(concurrent boolean DEFAULT true)
LANGUAGE plpgsql AS $$
DECLARE
    mode text := CASE WHEN concurrent THEN 'CONCURRENTLY' ELSE '' END;
    mv   text;
BEGIN
    FOREACH mv IN ARRAY ARRAY[
        'site_visit.mv_geom_site_visit_location',
        'site_visit.mv_ancestral_remains',
        'site_visit.mv_site_visit_details',
        'site_visit.mv_site_visit_location',
        'site_visit.mv_related_documents',
        'site_visit.mv_remarks_and_recommendations',
        'site_visit.mv_identification',
        'site_visit.mv_archaeological_data',
        'site_visit.mv_resource'
    ]
    LOOP
        RAISE NOTICE 'refreshing %', mv;
        EXECUTE format('REFRESH MATERIALIZED VIEW %s %s', mode, mv);
        COMMIT;
    END LOOP;
END $$;
