-- GENERATED by manage.py generate_databc_views - do not edit.

CREATE OR REPLACE VIEW site_visit.resource AS SELECT * FROM site_visit.mv_resource;

COMMENT ON VIEW site_visit.resource IS
'Stable read contract for site_visit. One row per resource instance. Backed by mv_resource.';

-- GRANT SELECT ON site_visit.resource TO <app_role>;
