-- GENERATED by manage.py generate_databc_views - do not edit.

CREATE OR REPLACE VIEW archaeological_site.resource_flat AS SELECT * FROM archaeological_site.mv_resource_flat;
CREATE OR REPLACE VIEW archaeological_site.site_location_flat AS SELECT * FROM archaeological_site.mv_heritage_site_location_flat;
CREATE OR REPLACE VIEW archaeological_site.bc_property_address_flat AS SELECT * FROM archaeological_site.mv_bc_property_address_flat;

COMMENT ON VIEW archaeological_site.resource_flat IS
'Flat archaeological_site records, one row per resource. Cardinality-n values are delimiter-joined text (" | " between tiles, "; " within a tile).';
