-- GENERATED by manage.py generate_databc_views - do not edit.
-- Graph cef9c510-e3e6-4057-ac08-89ad926180b4
-- Requires 00_arches_util.sql to be applied first.
--
-- INVARIANTS:
--   * every key ALWAYS present; null, never absent.
--   * cardinality-n children are ALWAYS a jsonb array, [] when empty.
--   * cardinality-1 branches are an object, or null.
--   * array order is tiles.sortorder, then tileid.

SET client_min_messages = warning;
SET maintenance_work_mem = '512MB';
SET work_mem             = '128MB';

CREATE SCHEMA IF NOT EXISTS archaeological_site;

-- ---------------------------------------------------------------------
-- external_url  (cardinality n)
-- ---------------------------------------------------------------------
DROP MATERIALIZED VIEW IF EXISTS archaeological_site.mv_external_url CASCADE;
CREATE MATERIALIZED VIEW archaeological_site.mv_external_url AS
WITH external_url AS (
    SELECT t.resourceinstanceid AS resourceinstanceid,
           jsonb_agg(jsonb_build_object(
            'external_url_type', arches_util.reference_flat(t.tiledata -> '1f5a7b92-ca41-11ed-933f-5254004d77d3'),
            'external_url', arches_util.url_obj(t.tiledata -> '3ee73f28-ca40-11ed-af48-5254004d77d3')
        ) ORDER BY COALESCE(t.sortorder, 2147483647), t.tileid) AS arr
    FROM public.tiles t
    WHERE t.nodegroupid = '3ee73f28-ca40-11ed-af48-5254004d77d3'::uuid
    GROUP BY t.resourceinstanceid
)
SELECT resourceinstanceid, arr AS external_url FROM external_url;

CREATE UNIQUE INDEX mv_external_url_pk ON archaeological_site.mv_external_url (resourceinstanceid);
