-- GENERATED by manage.py generate_databc_views - do not edit.
-- Graph cef9c510-e3e6-4057-ac08-89ad926180b4
-- Requires 00_arches_util.sql to be applied first.
--
-- INVARIANTS:
--   * every key ALWAYS present; null, never absent.
--   * cardinality-n children are ALWAYS a jsonb array, [] when empty.
--   * cardinality-1 branches are an object, or null.
--   * array order is tiles.sortorder, then tileid.

SET client_min_messages = warning;
SET maintenance_work_mem = '512MB';
SET work_mem             = '128MB';

CREATE SCHEMA IF NOT EXISTS archaeological_site;

DROP MATERIALIZED VIEW IF EXISTS archaeological_site.mv_geom_site_boundary CASCADE;
CREATE MATERIALIZED VIEW archaeological_site.mv_geom_site_boundary AS
WITH per_tile AS (
    SELECT t.resourceinstanceid, t.tileid,
           ST_Collect(ST_Transform(g.geom, 4326)) AS geom
    FROM public.tiles t
    JOIN public.geojson_geometries g
      ON g.tileid = t.tileid AND g.nodeid = 'b18223c2-13ef-11f0-8695-0242ac170007'::uuid
    WHERE t.nodegroupid = 'b18223c2-13ef-11f0-8695-0242ac170007'::uuid
    GROUP BY t.resourceinstanceid, t.tileid
),
per_res AS (
    SELECT resourceinstanceid, ST_Collect(geom) AS raw
    FROM per_tile GROUP BY resourceinstanceid
),
fixed AS (
    SELECT resourceinstanceid, raw,
           ST_MakeValid(ST_CollectionHomogenize(ST_MakeValid(raw))) AS g
    FROM per_res
)
SELECT resourceinstanceid,
       g::geometry(Geometry, 4326)   AS site_boundary_geom,
       ST_GeometryType(g)            AS site_boundary_geom_type,
       ST_IsValid(raw)               AS site_boundary_source_valid,
       (CASE WHEN ST_IsEmpty(ST_CollectionExtract(g, 1)) THEN NULL
             ELSE ST_CollectionExtract(g, 1) END)::geometry(MultiPoint, 4326)      AS site_boundary_points,
       (CASE WHEN ST_IsEmpty(ST_CollectionExtract(g, 2)) THEN NULL
             ELSE ST_CollectionExtract(g, 2) END)::geometry(MultiLineString, 4326) AS site_boundary_lines,
       (CASE WHEN ST_IsEmpty(ST_CollectionExtract(g, 3)) THEN NULL
             ELSE ST_CollectionExtract(g, 3) END)::geometry(MultiPolygon, 4326)    AS site_boundary_polygons
FROM fixed;

CREATE UNIQUE INDEX mv_geom_site_boundary_pk   ON archaeological_site.mv_geom_site_boundary (resourceinstanceid);
CREATE INDEX mv_geom_site_boundary_gix         ON archaeological_site.mv_geom_site_boundary USING GIST (site_boundary_geom);
CREATE INDEX mv_geom_site_boundary_poly_gix    ON archaeological_site.mv_geom_site_boundary USING GIST (site_boundary_polygons);
CREATE INDEX mv_geom_site_boundary_pt_gix      ON archaeological_site.mv_geom_site_boundary USING GIST (site_boundary_points);
CREATE INDEX mv_geom_site_boundary_line_gix    ON archaeological_site.mv_geom_site_boundary USING GIST (site_boundary_lines);
