-- GENERATED by manage.py generate_databc_views - do not edit.
-- Graph cef9c510-e3e6-4057-ac08-89ad926180b4
-- Requires 00_arches_util.sql to be applied first.
--
-- INVARIANTS:
--   * every key ALWAYS present; null, never absent.
--   * cardinality-n children are ALWAYS a jsonb array, [] when empty.
--   * cardinality-1 branches are an object, or null.
--   * array order is tiles.sortorder, then tileid.

SET client_min_messages = warning;
SET maintenance_work_mem = '512MB';
SET work_mem             = '128MB';

CREATE SCHEMA IF NOT EXISTS archaeological_site;

-- ---------------------------------------------------------------------
-- site_record_admin  (cardinality n)
-- ---------------------------------------------------------------------
DROP MATERIALIZED VIEW IF EXISTS archaeological_site.mv_site_record_admin CASCADE;
CREATE MATERIALIZED VIEW archaeological_site.mv_site_record_admin AS
WITH site_record_admin AS (
    SELECT t.resourceinstanceid AS resourceinstanceid,
           jsonb_agg(jsonb_build_object(
            'bcap_submission_status', arches_util.reference_flat(t.tiledata -> '167e3e88-98a3-11ee-a464-080027b7463b'),
            'restricted', NULLIF(t.tiledata ->> 'dc974e68-8f0f-11ee-85a0-080027b7463b', '')::boolean
        ) ORDER BY COALESCE(t.sortorder, 2147483647), t.tileid) AS arr
    FROM public.tiles t
    WHERE t.nodegroupid = '0684fec8-0d07-11ed-8804-5254008afee6'::uuid
    GROUP BY t.resourceinstanceid
)
SELECT resourceinstanceid, arr AS site_record_admin FROM site_record_admin;

CREATE UNIQUE INDEX mv_site_record_admin_pk ON archaeological_site.mv_site_record_admin (resourceinstanceid);
