-- GENERATED by manage.py generate_databc_views - do not edit.

CREATE OR REPLACE PROCEDURE archaeological_site.refresh_flat(concurrent boolean DEFAULT true)
LANGUAGE plpgsql AS $$
DECLARE
    mode text := CASE WHEN concurrent THEN 'CONCURRENTLY' ELSE '' END;
    mv   text;
BEGIN
    FOREACH mv IN ARRAY ARRAY[
        'archaeological_site.mv_resource_flat',
        'archaeological_site.mv_heritage_site_location_flat',
        'archaeological_site.mv_bc_property_address_flat'
    ]
    LOOP
        RAISE NOTICE 'refreshing %', mv;
        EXECUTE format('REFRESH MATERIALIZED VIEW %s %s', mode, mv);
        COMMIT;
    END LOOP;
END $$;
