-- GENERATED by manage.py generate_databc_views - do not edit.

CREATE OR REPLACE VIEW archaeological_site.resource AS SELECT * FROM archaeological_site.mv_resource;

COMMENT ON VIEW archaeological_site.resource IS
'Stable read contract for archaeological_site. One row per resource instance. Backed by mv_resource.';

-- GRANT SELECT ON archaeological_site.resource TO <app_role>;
