# Generated by Django 4.2.13 on 2024-06-18 10:12

from django.core.management import call_command
from django.db import migrations
from django.db.migrations.operations.special import RunPython

from bcap.settings import APP_ROOT

mapbox_overlays_dir = f"{APP_ROOT}/pkg/map_layers/mapbox_spec_json/overlays"


def forward(apps, schema_editor):
    call_command("bc_test_users", add_users=True)


def backward(apps, schema_editor):
    call_command("bc_test_users", delete_users=True)


class Migration(migrations.Migration):

    dependencies = [
        ("bcap", "0001_initial"),
        ("models", "10999_update_principaluser"),
        ("guardian", "0002_generic_permissions_index"),
    ]

    operations = [RunPython(forward, backward)]
