# Generated by Django 5.2.5 on 2025-10-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bcap", "1032_update_map_filter_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="BordenNumberCounter",
            fields=[
                (
                    "borden_grid",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("grid_sequence", models.BigIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Borden Number Counter",
                "verbose_name_plural": "Borden Number Counters",
                "db_table": "bcap_borden_number_counters",
            },
        ),
    ]
