# Generated by Django 5.2.13 on 2026-06-08 11:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bcap", "1412_load_industry_sector_skos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("graph_slug", models.CharField(max_length=255)),
                ("graph_publication_id", models.UUIDField(blank=True, null=True)),
                (
                    "frontend_version",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("resourceinstanceid", models.UUIDField(blank=True, null=True)),
                ("data", models.JSONField(default=dict)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource Draft",
                "verbose_name_plural": "Resource Drafts",
                "db_table": "bcap_resource_drafts",
                "indexes": [
                    models.Index(
                        fields=["user", "graph_slug"],
                        name="bcap_resour_user_id_871ff3_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("resourceinstanceid__isnull", False)),
                        fields=("user", "graph_slug", "resourceinstanceid"),
                        name="unique_draft_per_user_graph_resource",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("resourceinstanceid__isnull", True)),
                        fields=("user", "graph_slug"),
                        name="unique_new_draft_per_user_graph",
                    ),
                ],
            },
        ),
    ]
