# Generated by Django 5.2.14 on 2026-06-15 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bcap", "1414_add_edit_log_tileinstanceid_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="resourcedraft",
            constraint=models.UniqueConstraint(
                condition=models.Q(("resourceinstanceid__isnull", False)),
                fields=("user", "graph_slug", "resourceinstanceid"),
                name="unique_draft_per_user_graph_resource",
            ),
        ),
        migrations.AddConstraint(
            model_name="resourcedraft",
            constraint=models.UniqueConstraint(
                condition=models.Q(("resourceinstanceid__isnull", True)),
                fields=("user", "graph_slug"),
                name="unique_new_draft_per_user_graph",
            ),
        ),
    ]
