-- GENERATED by manage.py generate_databc_views - do not edit.

CREATE OR REPLACE VIEW hca_permit.resource_flat AS SELECT * FROM hca_permit.mv_resource_flat;

COMMENT ON VIEW hca_permit.resource_flat IS
'Flat hca_permit records, one row per resource. Cardinality-n values are delimiter-joined text (" | " between tiles, "; " within a tile).';
