-- GENERATED by manage.py generate_databc_views - do not edit.
-- Graph f4b391f1-79d1-4886-ab2d-d72a197a9f21
-- Requires 00_arches_util.sql to be applied first.
--
-- INVARIANTS:
--   * every key ALWAYS present; null, never absent.
--   * cardinality-n children are ALWAYS a jsonb array, [] when empty.
--   * cardinality-1 branches are an object, or null.
--   * array order is tiles.sortorder, then tileid.

SET client_min_messages = warning;
SET maintenance_work_mem = '512MB';
SET work_mem             = '128MB';

CREATE SCHEMA IF NOT EXISTS hca_permit;

-- ---------------------------------------------------------------------
-- permit_identification  (cardinality 1)
-- ---------------------------------------------------------------------
DROP MATERIALIZED VIEW IF EXISTS hca_permit.mv_permit_identification CASCADE;
CREATE MATERIALIZED VIEW hca_permit.mv_permit_identification AS
WITH permit_identification AS (
    SELECT DISTINCT ON (t.resourceinstanceid) t.resourceinstanceid AS resourceinstanceid,
           jsonb_build_object(
            'permit_number', t.tiledata ->> '673aa382-df62-11ef-9ad0-0242ac170009',
            'issuing_agency', arches_util.reference_flat(t.tiledata -> '7f0349ce-df62-11ef-9ad0-0242ac170009'),
            'hca_permit_type', arches_util.reference_flat(t.tiledata -> '9c8ad2f0-df62-11ef-9ad0-0242ac170009'),
            'permit_holder', arches_util.resource_ids(t.tiledata -> '3af6f67a-5926-11f0-bef3-0242ac170006')
        ) AS obj
    FROM public.tiles t
    WHERE t.nodegroupid = '588c9c3c-df62-11ef-9ad0-0242ac170009'::uuid
    ORDER BY t.resourceinstanceid, COALESCE(t.sortorder, 2147483647), t.tileid
)
SELECT resourceinstanceid, obj AS permit_identification FROM permit_identification;

CREATE UNIQUE INDEX mv_permit_identification_pk ON hca_permit.mv_permit_identification (resourceinstanceid);
