-- GENERATED by manage.py generate_databc_views - do not edit.
-- Graph f4b391f1-79d1-4886-ab2d-d72a197a9f21
-- Requires 00_arches_util.sql to be applied first.
--
-- INVARIANTS:
--   * every key ALWAYS present; null, never absent.
--   * cardinality-n children are ALWAYS a jsonb array, [] when empty.
--   * cardinality-1 branches are an object, or null.
--   * array order is tiles.sortorder, then tileid.

SET client_min_messages = warning;
SET maintenance_work_mem = '512MB';
SET work_mem             = '128MB';

CREATE SCHEMA IF NOT EXISTS hca_permit;

DROP MATERIALIZED VIEW IF EXISTS hca_permit.mv_resource CASCADE;
CREATE MATERIALIZED VIEW hca_permit.mv_resource AS
-- resource_instances is the row driver: one row per resource including
-- resources with zero tiles; carries the graphid filter.
SELECT
    r.resourceinstanceid,
    b0.permit_identification,
    jsonb_build_object(
        'resourceinstanceid', r.resourceinstanceid,
        'permit_identification', b0.permit_identification
    ) AS resource
FROM public.resource_instances r
LEFT JOIN hca_permit.mv_permit_identification b0 ON b0.resourceinstanceid = r.resourceinstanceid
WHERE r.graphid = 'f4b391f1-79d1-4886-ab2d-d72a197a9f21'::uuid;

CREATE UNIQUE INDEX mv_resource_pk  ON hca_permit.mv_resource (resourceinstanceid);
CREATE INDEX mv_resource_res        ON hca_permit.mv_resource USING GIN (resource jsonb_path_ops);
