-- GENERATED by manage.py generate_databc_views - do not edit.
-- Requires hca_permit/mv_resource.sql to be applied first.
--
-- CONTRACT:
--   * cardinality-1 fields: REAL TYPES (date, numeric, boolean, text)
--   * cardinality-n fields: TEXT CSV (' | ' between tiles, '; ' within)
--   * POSITIONAL ALIGNMENT: null elements emit empty slots.
--   * references: x (labels) + x_ids pairs.

SET client_min_messages = warning;

DROP MATERIALIZED VIEW IF EXISTS hca_permit.mv_resource_flat CASCADE;
CREATE MATERIALIZED VIEW hca_permit.mv_resource_flat AS
SELECT
    r.resourceinstanceid,
    r.permit_identification ->> 'permit_number' AS permit_number,
    arches_util.a2csv(r.permit_identification -> 'issuing_agency', 'label', ' | ') AS issuing_agency,
    arches_util.a2csv(r.permit_identification -> 'issuing_agency', 'list_item_id', ' | ') AS issuing_agency_ids,
    arches_util.a2csv(r.permit_identification -> 'hca_permit_type', 'label', ' | ') AS hca_permit_type,
    arches_util.a2csv(r.permit_identification -> 'hca_permit_type', 'list_item_id', ' | ') AS hca_permit_type_ids,
    arches_util.resource_names_csv(r.permit_identification -> 'permit_holder', ' | ') AS permit_holder,
    arches_util.a2csv(r.permit_identification -> 'permit_holder', NULL, ' | ') AS permit_holder_ids
FROM hca_permit.mv_resource r;

CREATE UNIQUE INDEX mv_resource_flat_pk ON hca_permit.mv_resource_flat (resourceinstanceid);
