-- GENERATED by manage.py generate_databc_views - do not edit.

CREATE OR REPLACE VIEW hca_permit.resource AS SELECT * FROM hca_permit.mv_resource;

COMMENT ON VIEW hca_permit.resource IS
'Stable read contract for hca_permit. One row per resource instance. Backed by mv_resource.';

-- GRANT SELECT ON hca_permit.resource TO <app_role>;
