-- =====================================================================
--  BUGFIX for the EXISTING site_visit stack.
--
--  Found while building archaeological_site and confirmed on PostgreSQL 16 /
--  PostGIS 3.4:
--
--      ST_Collect(agg) over 2 plain polygons         -> ST_MultiPolygon
--      ST_Collect(agg) over 2 ST_Collect'd polygons  -> ST_GeometryCollection
--
--  site_visit.mv_site_visit_location aggregates ST_Collect() across tiles over
--  geometries that were THEMSELVES produced by ST_Collect() (per-tile, from
--  geojson_geometries). So site_visit_geom is coming out as a GEOMETRYCOLLECTION
--  today, even where every part is a polygon.
--
--  That breaks a lot of GIS clients and some PostGIS functions, and it is exactly
--  the kind of thing that surfaces only once a downstream app tries to use it.
--
--  ST_CollectionHomogenize collapses homogeneous parts to MULTIPOLYGON and
--  correctly LEAVES a GEOMETRYCOLLECTION only when the tiles genuinely mix
--  geometry types.
--
--  Check what you have today:
--      SELECT ST_GeometryType(site_visit_geom), count(*)
--      FROM site_visit.mv_site_visit_location
--      WHERE site_visit_geom IS NOT NULL GROUP BY 1;
--
--  Then apply: in site_visit_mv_stack_v2.sql, section 3.1, change
--
--      ST_Collect(geom) FILTER (WHERE geom IS NOT NULL)  AS site_visit_geom
--  to
--      ST_CollectionHomogenize(ST_Collect(geom) FILTER (WHERE geom IS NOT NULL))
--                                                       AS site_visit_geom
--
--  and rebuild mv_site_visit_location + mv_resource_v1. It is a column TYPE
--  change (geometry -> geometry), so the wrapper view swaps cleanly, but any
--  downstream code that special-cases GEOMETRYCOLLECTION should be told.
-- =====================================================================
