/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/bcap/api/dashboard': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns dashboard cards for the current user based on their role. */
        get: operations['api_dashboard_retrieve'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/bcap/api/process_requirement/{id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET/PUT/PATCH/DELETE a Process Requirement and its sub-requirements.
         *
         *     PATCH applies a partial diff (only the tiles present in the body); PUT
         *     replaces. Either way the serializer saves the nested sub-requirement tiles.
         */
        get: operations['api_process_requirement_retrieve'];
        /**
         * @description GET/PUT/PATCH/DELETE a Process Requirement and its sub-requirements.
         *
         *     PATCH applies a partial diff (only the tiles present in the body); PUT
         *     replaces. Either way the serializer saves the nested sub-requirement tiles.
         */
        put: operations['api_process_requirement_update'];
        post?: never;
        /**
         * @description GET/PUT/PATCH/DELETE a Process Requirement and its sub-requirements.
         *
         *     PATCH applies a partial diff (only the tiles present in the body); PUT
         *     replaces. Either way the serializer saves the nested sub-requirement tiles.
         */
        delete: operations['api_process_requirement_destroy'];
        options?: never;
        head?: never;
        /**
         * @description GET/PUT/PATCH/DELETE a Process Requirement and its sub-requirements.
         *
         *     PATCH applies a partial diff (only the tiles present in the body); PUT
         *     replaces. Either way the serializer saves the nested sub-requirement tiles.
         */
        patch: operations['api_process_requirement_partial_update'];
        trace?: never;
    };
    '/bcap/user_profile': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns the authenticated user's profile, group memberships, and linked Contributor resource id. */
        get: operations['user_profile_retrieve'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DashboardCard: {
            /** @description Permit application resourceinstanceid; the card's drill-in GUID. */
            id: string;
            /** @description Name of the chosen (first unsatisfied) process requirement. */
            requirement_name?: string;
            /** @description Process due date of the chosen requirement. */
            requirement_due_date?: string;
            /** @description Permit application's project name. */
            project_name?: string;
            /** @description Permit application's human-readable application reference (e.g. "APP-1"); not a GUID. The application's GUID is the card's `id`. */
            application_number?: string;
            /** @description Permit application's industrial sector (reference label). */
            industrial_sector?: string;
            /** @description Resourceinstanceid of the related HCA Permit; its drill-in GUID. */
            permit_id?: string | null;
            /** @description Permit number of the related HCA Permit. */
            permit_number?: string;
            /** @description Permit holder name(s) on the related HCA Permit (Contributor). */
            permit_holder?: string;
            /** @description Resourceinstanceids of the permit holder Contributor(s); their drill-in GUIDs. */
            permit_holder_ids?: string[];
            /** @description Project officer on the permit's application_admin group (Contributor name). */
            project_officer?: string;
            /** @description Resourceinstanceid of the project officer Contributor; its drill-in GUID. */
            project_officer_id?: string | null;
            /** @description Assessment notes on the chosen requirement. */
            assessment_notes?: string;
            /** @description Ministry assignee on the chosen requirement tile (Contributor name). */
            ministry_assignee_name?: string;
            /** @description Resourceinstanceid of the ministry assignee Contributor; its drill-in GUID. */
            ministry_assignee_id?: string | null;
            /** @description Edit-log date the chosen tile's ministry_assignee last changed. */
            ministry_assignee_change_date?: string;
            /** @description Resourceinstanceid of the chosen Process Requirement; the drill-in target. */
            requirement_id?: string;
            /** @description Relative urgency from the target completion date and the current date. */
            urgency?: number;
            /** @description Permit application's priority level (reference label). */
            priority_level?: string;
        };
        /**
         * @description One page of dashboard cards for the current user.
         *
         *     `count` is the total number of cards matching the query across all pages;
         *     `page` and `limit` echo the requested page number and page size; `results`
         *     holds the cards for this page (at most `limit` of them). Each card's fields
         *     are documented on the DashboardCard dataclass (as field help_text), so the
         *     per-field descriptions surface in the generated OpenAPI spec.
         */
        DashboardPage: {
            count?: number;
            page?: number;
            limit?: number;
            results?: components['schemas']['DashboardCard'][];
        };
        /**
         * @description The {node_value, display_value, details} object node value fields emit when as_representation is True.
         *
         *     Mirrors the dict built in arches_querysets TileTree.get_value_with_context;
         *     keep in sync if that shape changes upstream.
         */
        NodeValueEnvelope: {
            node_value: unknown;
            readonly display_value: string;
            readonly details: {
                [key: string]: unknown;
            }[];
        };
        PatchedProcessRequirement: {
            /** Format: uuid */
            resourceinstanceid?: string | null;
            aliased_data?: components['schemas']['ResourceAliasedData'];
            readonly graph_has_different_publication?: boolean;
            readonly name?: unknown;
            readonly descriptors?: unknown;
            readonly legacyid?: string | null;
            /** Format: date-time */
            readonly createdtime?: string;
            /** Format: uuid */
            graph?: string | null;
            /** Format: uuid */
            readonly graph_publication?: string | null;
            /** Format: uuid */
            readonly resource_instance_lifecycle_state?: string;
            readonly principaluser?: number | null;
        };
        ProcessRequirement: {
            /** Format: uuid */
            resourceinstanceid?: string | null;
            aliased_data?: components['schemas']['ResourceAliasedData'];
            readonly graph_has_different_publication: boolean;
            readonly name: unknown;
            readonly descriptors: unknown;
            readonly legacyid: string | null;
            /** Format: date-time */
            readonly createdtime: string;
            /** Format: uuid */
            graph?: string | null;
            /** Format: uuid */
            readonly graph_publication: string | null;
            /** Format: uuid */
            readonly resource_instance_lifecycle_state: string;
            readonly principaluser: number | null;
        };
        Process_Requirement_Is_Template_Requirement_Aliased_Data: {
            has_submission_requirement:
                | components['schemas']['NodeValueEnvelope']
                | null;
            is_internal_requirement:
                | components['schemas']['NodeValueEnvelope']
                | null;
            /**
             * Default Target Processing Time (days)
             * @description Enter number
             */
            default_target_processing_time?:
                | components['schemas']['NodeValueEnvelope']
                | null;
            is_template_requirement:
                | components['schemas']['NodeValueEnvelope']
                | null;
        };
        Process_Requirement_Is_Template_Requirement_Tile: {
            /** Format: uuid */
            tileid?: string | null;
            /** Format: uuid */
            resourceinstance?: string | null;
            /** Format: uuid */
            nodegroup?: string | null;
            /** Format: uuid */
            parenttile?: string | null;
            aliased_data?: components['schemas']['Process_Requirement_Is_Template_Requirement_Aliased_Data'];
            sortorder?: number | null;
            provisionaledits?: unknown;
        };
        Process_Requirement_Requirement_Execution_Duration_Aliased_Data: {
            /** @description Enter date */
            requirement_process_start_date?:
                | components['schemas']['NodeValueEnvelope']
                | null;
            /** @description Enter date */
            requirement_process_due_date?:
                | components['schemas']['NodeValueEnvelope']
                | null;
            /** @description Enter date */
            requirement_process_completion_date?:
                | components['schemas']['NodeValueEnvelope']
                | null;
        };
        Process_Requirement_Requirement_Execution_Duration_Tile: {
            /** Format: uuid */
            tileid?: string | null;
            /** Format: uuid */
            resourceinstance?: string | null;
            /** Format: uuid */
            nodegroup?: string | null;
            /** Format: uuid */
            parenttile?: string | null;
            aliased_data?: components['schemas']['Process_Requirement_Requirement_Execution_Duration_Aliased_Data'];
            sortorder?: number | null;
            provisionaledits?: unknown;
        };
        Process_Requirement_Requirement_Identification_Aliased_Data: {
            /** @description Enter text */
            requirement_name: components['schemas']['NodeValueEnvelope'] | null;
            /** @description Enter text */
            requirement_identification:
                | components['schemas']['NodeValueEnvelope']
                | null;
            is_template_requirement?:
                | components['schemas']['Process_Requirement_Is_Template_Requirement_Tile']
                | null;
        };
        Process_Requirement_Requirement_Identification_Tile: {
            /** Format: uuid */
            tileid?: string | null;
            /** Format: uuid */
            resourceinstance?: string | null;
            /** Format: uuid */
            nodegroup?: string | null;
            /** Format: uuid */
            parenttile?: string | null;
            aliased_data?: components['schemas']['Process_Requirement_Requirement_Identification_Aliased_Data'];
            sortorder?: number | null;
            provisionaledits?: unknown;
        };
        Process_Requirement_Requirment_Submission_Aliased_Data: {
            requirment_submission?:
                | components['schemas']['NodeValueEnvelope']
                | null;
        };
        Process_Requirement_Requirment_Submission_Tile: {
            /** Format: uuid */
            tileid?: string | null;
            /** Format: uuid */
            resourceinstance?: string | null;
            /** Format: uuid */
            nodegroup?: string | null;
            /** Format: uuid */
            parenttile?: string | null;
            aliased_data?: components['schemas']['Process_Requirement_Requirment_Submission_Aliased_Data'];
            sortorder?: number | null;
            provisionaledits?: unknown;
        };
        Process_Requirement_Sub_Requirement_Aliased_Data: {
            /**
             * Description
             * @description Enter text
             */
            sub_requirement_description?:
                | components['schemas']['NodeValueEnvelope']
                | null;
            /**
             * Assessment Notes
             * @description Enter text
             */
            sub_requirement_assessment_notes?:
                | components['schemas']['NodeValueEnvelope']
                | null;
            /** Requirement Satisfied */
            sub_requirement_satisfied?:
                | components['schemas']['NodeValueEnvelope']
                | null;
            /**
             * Sort Order
             * @description Enter number
             */
            sub_requirement_sort_order:
                | components['schemas']['NodeValueEnvelope']
                | null;
            /** Mandatory */
            sub_requirement_mandatory?:
                | components['schemas']['NodeValueEnvelope']
                | null;
            sub_requirement_reference?:
                | components['schemas']['NodeValueEnvelope']
                | null;
            /**
             * Requirement
             * @description Enter text
             */
            sub_requirement_name:
                | components['schemas']['NodeValueEnvelope']
                | null;
        };
        Process_Requirement_Sub_Requirement_Assessment_N1_Aliased_Data: {
            requirement_status?:
                | components['schemas']['NodeValueEnvelope']
                | null;
            /** @description Enter text */
            assessment_notes?:
                | components['schemas']['NodeValueEnvelope']
                | null;
        };
        Process_Requirement_Sub_Requirement_Assessment_N1_Tile: {
            /** Format: uuid */
            tileid?: string | null;
            /** Format: uuid */
            resourceinstance?: string | null;
            /** Format: uuid */
            nodegroup?: string | null;
            /** Format: uuid */
            parenttile?: string | null;
            aliased_data?: components['schemas']['Process_Requirement_Sub_Requirement_Assessment_N1_Aliased_Data'];
            sortorder?: number | null;
            provisionaledits?: unknown;
        };
        Process_Requirement_Sub_Requirement_Tile: {
            /** Format: uuid */
            tileid?: string | null;
            /** Format: uuid */
            resourceinstance?: string | null;
            /** Format: uuid */
            nodegroup?: string | null;
            /** Format: uuid */
            parenttile?: string | null;
            aliased_data?: components['schemas']['Process_Requirement_Sub_Requirement_Aliased_Data'];
            sortorder?: number | null;
            provisionaledits?: unknown;
        };
        ResourceAliasedData: {
            requirement_identification?:
                | components['schemas']['Process_Requirement_Requirement_Identification_Tile']
                | null;
            requirement_execution_duration?:
                | components['schemas']['Process_Requirement_Requirement_Execution_Duration_Tile']
                | null;
            requirment_submission?:
                | components['schemas']['Process_Requirement_Requirment_Submission_Tile']
                | null;
            sub_requirement_assessment_n1?:
                | components['schemas']['Process_Requirement_Sub_Requirement_Assessment_N1_Tile']
                | null;
            sub_requirement?:
                | components['schemas']['Process_Requirement_Sub_Requirement_Tile'][]
                | null;
        };
        UserProfileResponse: {
            username: string;
            first_name: string;
            last_name: string;
            readonly groups: string[];
            /** @description TODO fill this in. */
            readonly contributor_id: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_dashboard_retrieve: {
        parameters: {
            query?: {
                contributor_id?: string | null;
                limit?: number;
                order_by?: string | null;
                page?: number;
                /** @description * `UNASSIGNED` - Unassigned */
                status?: 'UNASSIGNED' | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['DashboardPage'];
                };
            };
        };
    };
    api_process_requirement_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ProcessRequirement'];
                };
            };
        };
    };
    api_process_requirement_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                'application/json': components['schemas']['ProcessRequirement'];
                'multipart/form-data': components['schemas']['ProcessRequirement'];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ProcessRequirement'];
                };
            };
        };
    };
    api_process_requirement_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_process_requirement_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                'application/json': components['schemas']['PatchedProcessRequirement'];
                'multipart/form-data': components['schemas']['PatchedProcessRequirement'];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ProcessRequirement'];
                };
            };
        };
    };
    user_profile_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['UserProfileResponse'];
                };
            };
        };
    };
}
