/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/bcap/api/dashboard': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns dashboard cards for the current user based on their role. */
        get: operations['api_dashboard_retrieve'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/bcap/user_profile': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns the authenticated user's profile, group memberships, and linked Contributor resource id. */
        get: operations['user_profile_retrieve'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DashboardCard: {
            id: string;
            cap_label?: string;
            cap_date?: string;
            body_title?: string;
            body_subtitle1?: string;
            body_subtitle2?: string;
            body1?: string;
            body2?: string;
            body3?: string;
            body4?: string;
            body5?: string;
            footer_name?: string;
            footer_date?: string;
            route?: string;
            urgency?: number;
            cap_priority?: string;
        };
        /**
         * @description One page of dashboard cards for the current user.
         *
         *     `count` is the total number of cards matching the query across all pages;
         *     `page` and `limit` echo the requested page number and page size; `results`
         *     holds the cards for this page (at most `limit` of them).
         */
        DashboardPage: {
            count?: number;
            page?: number;
            limit?: number;
            results?: components['schemas']['DashboardCard'][];
        };
        UserProfileResponse: {
            username: string;
            first_name: string;
            last_name: string;
            readonly groups: string[];
            /** @description TODO fill this in. */
            readonly contributor_id: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_dashboard_retrieve: {
        parameters: {
            query?: {
                contributor_id?: string | null;
                limit?: number;
                order_by?: string | null;
                page?: number;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['DashboardPage'];
                };
            };
        };
    };
    user_profile_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['UserProfileResponse'];
                };
            };
        };
    };
}
