/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/bcap/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns dashboard cards for the current user based on their role. */
        get: operations["api_dashboard_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bcap/user_profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns the authenticated user's profile, group memberships, and linked Contributor resource id. */
        get: operations["user_profile_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DashboardCardResponse: {
            id: string;
            cap_priority: boolean;
            cap_label: string;
            cap_date: string;
            icon: string;
            project_name: string;
            project_id: string;
            sector: string;
            body1: string;
            body2: string;
            body3: string;
            body4: string;
            footer_date: string;
            footer_name: string;
            urgency: number;
        };
        UserProfileResponse: {
            username: string;
            first_name: string;
            last_name: string;
            readonly groups: string[];
            readonly contributor_id: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_dashboard_list: {
        parameters: {
            query?: {
                filter_by?: string;
                limit?: number;
                order_by?: string;
                page?: number;
                /**
                 * @description * `assigned` - assigned
                 *     * `unassigned` - unassigned
                 */
                status?: "assigned" | "unassigned";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardCardResponse"][];
                };
            };
        };
    };
    user_profile_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
        };
    };
}
