/**
 * Generated by orval from the OpenAPI spec in schema.yml -- do not edit by hand.
 * Regenerate with `npm run openapi:gen` (or `npm run api:gen` to also rebuild schema.yml).
 */
import * as zod from 'zod';



/**
 * GET the requesting user's HCA Permits.

Read-only and owner-scoped: returns only the permits the user created.
 */
export const apiResourceHcaPermitListQueryParams = zod.object({
  "limit": zod.number().optional().describe('Number of results to return per page.'),
  "offset": zod.number().optional().describe('The initial index from which to return the results.')
})

export const apiResourceHcaPermitListResponseResultsItemAliasedDataPermitIdentificationSortorderMin = -2147483648;
export const apiResourceHcaPermitListResponseResultsItemAliasedDataPermitIdentificationSortorderMax = 2147483647;



export const apiResourceHcaPermitListResponse = zod.object({
  "count": zod.number(),
  "next": zod.string().url().nullish(),
  "previous": zod.string().url().nullish(),
  "results": zod.array(zod.object({
  "resourceinstanceid": zod.string().uuid().nullish(),
  "aliased_data": zod.object({
  "permit_identification": zod.object({
  "tileid": zod.string().uuid().nullish(),
  "resourceinstance": zod.string().uuid().nullish(),
  "nodegroup": zod.string().uuid().nullish(),
  "parenttile": zod.string().uuid().nullish(),
  "aliased_data": zod.object({
  "permit_number": zod.object({
  "node_value": zod.string().nullable(),
  "display_value": zod.string().optional(),
  "details": zod.array(zod.record(zod.string(), zod.unknown())).optional()
}).nullish().describe('Enter text'),
  "hca_permit_type": zod.object({
  "node_value": zod.array(zod.object({
  "uri": zod.string().optional(),
  "list_id": zod.string().uuid().optional(),
  "labels": zod.array(zod.object({
  "id": zod.string().uuid().optional(),
  "value": zod.string().optional(),
  "language_id": zod.string().optional(),
  "list_item_id": zod.string().uuid().optional(),
  "valuetype_id": zod.string().optional()
})).optional()
})).nullable(),
  "display_value": zod.string().optional(),
  "details": zod.array(zod.record(zod.string(), zod.unknown())).optional()
}).nullish().describe('Select an option'),
  "issuing_agency": zod.object({
  "node_value": zod.array(zod.object({
  "uri": zod.string().optional(),
  "list_id": zod.string().uuid().optional(),
  "labels": zod.array(zod.object({
  "id": zod.string().uuid().optional(),
  "value": zod.string().optional(),
  "language_id": zod.string().optional(),
  "list_item_id": zod.string().uuid().optional(),
  "valuetype_id": zod.string().optional()
})).optional()
})).nullable(),
  "display_value": zod.string().optional(),
  "details": zod.array(zod.record(zod.string(), zod.unknown())).optional()
}).nullish().describe('Select an option'),
  "permit_holder": zod.object({
  "node_value": zod.array(zod.object({
  "resourceId": zod.string().uuid().optional(),
  "ontologyProperty": zod.string().nullish(),
  "resourceXresourceId": zod.string().nullish(),
  "inverseOntologyProperty": zod.string().nullish()
})).nullable(),
  "display_value": zod.string().optional(),
  "details": zod.array(zod.object({
  "resource_id": zod.string().uuid().nullable(),
  "display_value": zod.string()
}).describe('One related resource summarized into a resource-instance node\'s `details`.')).optional()
}).nullish()
}).optional(),
  "sortorder": zod.number().min(apiResourceHcaPermitListResponseResultsItemAliasedDataPermitIdentificationSortorderMin).max(apiResourceHcaPermitListResponseResultsItemAliasedDataPermitIdentificationSortorderMax).nullish(),
  "provisionaledits": zod.record(zod.string(), zod.object({
  "value": zod.record(zod.string(), zod.unknown()).optional(),
  "status": zod.string().optional(),
  "action": zod.string().optional(),
  "reviewer": zod.number().nullish(),
  "timestamp": zod.string().nullish(),
  "reviewtimestamp": zod.string().nullish()
})).nullish()
}).nullish()
}).optional(),
  "graph_has_different_publication": zod.boolean(),
  "name": zod.string().nullable(),
  "descriptors": zod.object({
  "en": zod.object({
  "name": zod.string().optional(),
  "description": zod.string().optional(),
  "map_popup": zod.string().optional()
}).optional()
}).nullable(),
  "legacyid": zod.string().nullable(),
  "createdtime": zod.string().datetime({}),
  "graph": zod.string().uuid().nullish(),
  "graph_publication": zod.string().uuid().nullable(),
  "resource_instance_lifecycle_state": zod.string().uuid(),
  "principaluser": zod.number().nullable()
}))
})

/**
 * GET an HCA Permit and its nested tiles.

Read-only, and scoped to the requesting user's own permits: requesting one
created by another user returns 404.
 */
export const apiResourceHcaPermitRetrieveParams = zod.object({
  "id": zod.string().uuid()
})

export const apiResourceHcaPermitRetrieveResponseAliasedDataPermitIdentificationSortorderMin = -2147483648;
export const apiResourceHcaPermitRetrieveResponseAliasedDataPermitIdentificationSortorderMax = 2147483647;



export const apiResourceHcaPermitRetrieveResponse = zod.object({
  "resourceinstanceid": zod.string().uuid().nullish(),
  "aliased_data": zod.object({
  "permit_identification": zod.object({
  "tileid": zod.string().uuid().nullish(),
  "resourceinstance": zod.string().uuid().nullish(),
  "nodegroup": zod.string().uuid().nullish(),
  "parenttile": zod.string().uuid().nullish(),
  "aliased_data": zod.object({
  "permit_number": zod.object({
  "node_value": zod.string().nullable(),
  "display_value": zod.string().optional(),
  "details": zod.array(zod.record(zod.string(), zod.unknown())).optional()
}).nullish().describe('Enter text'),
  "hca_permit_type": zod.object({
  "node_value": zod.array(zod.object({
  "uri": zod.string().optional(),
  "list_id": zod.string().uuid().optional(),
  "labels": zod.array(zod.object({
  "id": zod.string().uuid().optional(),
  "value": zod.string().optional(),
  "language_id": zod.string().optional(),
  "list_item_id": zod.string().uuid().optional(),
  "valuetype_id": zod.string().optional()
})).optional()
})).nullable(),
  "display_value": zod.string().optional(),
  "details": zod.array(zod.record(zod.string(), zod.unknown())).optional()
}).nullish().describe('Select an option'),
  "issuing_agency": zod.object({
  "node_value": zod.array(zod.object({
  "uri": zod.string().optional(),
  "list_id": zod.string().uuid().optional(),
  "labels": zod.array(zod.object({
  "id": zod.string().uuid().optional(),
  "value": zod.string().optional(),
  "language_id": zod.string().optional(),
  "list_item_id": zod.string().uuid().optional(),
  "valuetype_id": zod.string().optional()
})).optional()
})).nullable(),
  "display_value": zod.string().optional(),
  "details": zod.array(zod.record(zod.string(), zod.unknown())).optional()
}).nullish().describe('Select an option'),
  "permit_holder": zod.object({
  "node_value": zod.array(zod.object({
  "resourceId": zod.string().uuid().optional(),
  "ontologyProperty": zod.string().nullish(),
  "resourceXresourceId": zod.string().nullish(),
  "inverseOntologyProperty": zod.string().nullish()
})).nullable(),
  "display_value": zod.string().optional(),
  "details": zod.array(zod.object({
  "resource_id": zod.string().uuid().nullable(),
  "display_value": zod.string()
}).describe('One related resource summarized into a resource-instance node\'s `details`.')).optional()
}).nullish()
}).optional(),
  "sortorder": zod.number().min(apiResourceHcaPermitRetrieveResponseAliasedDataPermitIdentificationSortorderMin).max(apiResourceHcaPermitRetrieveResponseAliasedDataPermitIdentificationSortorderMax).nullish(),
  "provisionaledits": zod.record(zod.string(), zod.object({
  "value": zod.record(zod.string(), zod.unknown()).optional(),
  "status": zod.string().optional(),
  "action": zod.string().optional(),
  "reviewer": zod.number().nullish(),
  "timestamp": zod.string().nullish(),
  "reviewtimestamp": zod.string().nullish()
})).nullish()
}).nullish()
}).optional(),
  "graph_has_different_publication": zod.boolean(),
  "name": zod.string().nullable(),
  "descriptors": zod.object({
  "en": zod.object({
  "name": zod.string().optional(),
  "description": zod.string().optional(),
  "map_popup": zod.string().optional()
}).optional()
}).nullable(),
  "legacyid": zod.string().nullable(),
  "createdtime": zod.string().datetime({}),
  "graph": zod.string().uuid().nullish(),
  "graph_publication": zod.string().uuid().nullable(),
  "resource_instance_lifecycle_state": zod.string().uuid(),
  "principaluser": zod.number().nullable()
})

