/**
 * Generated by orval from the OpenAPI spec in schema.yml -- do not edit by hand.
 * Regenerate with `npm run openapi:gen` (or `npm run api:gen` to also rebuild schema.yml).
 */
import * as zod from 'zod';



/**
 * Returns the authenticated user's profile, group memberships, and linked Contributor resource id.
 */
export const userProfileRetrieveResponse = zod.object({
  "username": zod.string(),
  "first_name": zod.string(),
  "last_name": zod.string(),
  "groups": zod.array(zod.string())
})

