/**
 * Generated by orval from the OpenAPI spec in schema.yml -- do not edit by hand.
 * Regenerate with `npm run openapi:gen` (or `npm run api:gen` to also rebuild schema.yml).
 */
import * as zod from 'zod';

/**
 * GET the current user's drafts for a graph; POST a new draft.
 */
export const apiResourceDraftListParams = zod.object({
    graph_slug: zod.string(),
});

export const apiResourceDraftListResponseFrontendVersionMax = 50;

export const apiResourceDraftListResponseItem = zod.object({
    id: zod.string().uuid(),
    graph_has_different_publication: zod
        .boolean()
        .describe(
            'True when the published graph has moved on since the draft was saved.',
        ),
    data: zod.record(zod.string(), zod.unknown()).optional(),
    graph_slug: zod.string(),
    graph_publication_id: zod.string().uuid().nullable(),
    frontend_version: zod
        .string()
        .max(apiResourceDraftListResponseFrontendVersionMax)
        .nullish(),
    resourceinstanceid: zod.string().uuid().nullish(),
    created: zod.string().datetime({}),
    updated: zod.string().datetime({}),
});
export const apiResourceDraftListResponse = zod.array(
    apiResourceDraftListResponseItem,
);

/**
 * GET the current user's drafts for a graph; POST a new draft.
 */
export const apiResourceDraftCreateParams = zod.object({
    graph_slug: zod.string(),
});

export const apiResourceDraftCreateBodyFrontendVersionMax = 50;

export const apiResourceDraftCreateBody = zod.object({
    data: zod.record(zod.string(), zod.unknown()).optional(),
    frontend_version: zod
        .string()
        .max(apiResourceDraftCreateBodyFrontendVersionMax)
        .nullish(),
    resourceinstanceid: zod.string().uuid().nullish(),
});

/**
 * GET/PUT/PATCH/DELETE a single draft. PUT replaces the whole blob; PATCH
shallow-merges by section key -- untouched sections are kept, but a section
present in the body is replaced wholesale (no deep merge), so the client must
send the complete section, not just changed fields within it.
 */
export const apiResourceDraftRetrieveParams = zod.object({
    graph_slug: zod.string(),
    id: zod.string().uuid(),
});

export const apiResourceDraftRetrieveResponseFrontendVersionMax = 50;

export const apiResourceDraftRetrieveResponse = zod.object({
    id: zod.string().uuid(),
    graph_has_different_publication: zod
        .boolean()
        .describe(
            'True when the published graph has moved on since the draft was saved.',
        ),
    data: zod.record(zod.string(), zod.unknown()).optional(),
    graph_slug: zod.string(),
    graph_publication_id: zod.string().uuid().nullable(),
    frontend_version: zod
        .string()
        .max(apiResourceDraftRetrieveResponseFrontendVersionMax)
        .nullish(),
    resourceinstanceid: zod.string().uuid().nullish(),
    created: zod.string().datetime({}),
    updated: zod.string().datetime({}),
});

/**
 * GET/PUT/PATCH/DELETE a single draft. PUT replaces the whole blob; PATCH
shallow-merges by section key -- untouched sections are kept, but a section
present in the body is replaced wholesale (no deep merge), so the client must
send the complete section, not just changed fields within it.
 */
export const apiResourceDraftUpdateParams = zod.object({
    graph_slug: zod.string(),
    id: zod.string().uuid(),
});

export const apiResourceDraftUpdateBodyFrontendVersionMax = 50;

export const apiResourceDraftUpdateBody = zod.object({
    data: zod.record(zod.string(), zod.unknown()).optional(),
    frontend_version: zod
        .string()
        .max(apiResourceDraftUpdateBodyFrontendVersionMax)
        .nullish(),
    resourceinstanceid: zod.string().uuid().nullish(),
});

export const apiResourceDraftUpdateResponseFrontendVersionMax = 50;

export const apiResourceDraftUpdateResponse = zod.object({
    id: zod.string().uuid(),
    graph_has_different_publication: zod
        .boolean()
        .describe(
            'True when the published graph has moved on since the draft was saved.',
        ),
    data: zod.record(zod.string(), zod.unknown()).optional(),
    graph_slug: zod.string(),
    graph_publication_id: zod.string().uuid().nullable(),
    frontend_version: zod
        .string()
        .max(apiResourceDraftUpdateResponseFrontendVersionMax)
        .nullish(),
    resourceinstanceid: zod.string().uuid().nullish(),
    created: zod.string().datetime({}),
    updated: zod.string().datetime({}),
});

/**
 * GET/PUT/PATCH/DELETE a single draft. PUT replaces the whole blob; PATCH
shallow-merges by section key -- untouched sections are kept, but a section
present in the body is replaced wholesale (no deep merge), so the client must
send the complete section, not just changed fields within it.
 */
export const apiResourceDraftPartialUpdateParams = zod.object({
    graph_slug: zod.string(),
    id: zod.string().uuid(),
});

export const apiResourceDraftPartialUpdateBodyFrontendVersionMax = 50;

export const apiResourceDraftPartialUpdateBody = zod.object({
    data: zod.record(zod.string(), zod.unknown()).optional(),
    frontend_version: zod
        .string()
        .max(apiResourceDraftPartialUpdateBodyFrontendVersionMax)
        .nullish(),
    resourceinstanceid: zod.string().uuid().nullish(),
});

export const apiResourceDraftPartialUpdateResponseFrontendVersionMax = 50;

export const apiResourceDraftPartialUpdateResponse = zod.object({
    id: zod.string().uuid(),
    graph_has_different_publication: zod
        .boolean()
        .describe(
            'True when the published graph has moved on since the draft was saved.',
        ),
    data: zod.record(zod.string(), zod.unknown()).optional(),
    graph_slug: zod.string(),
    graph_publication_id: zod.string().uuid().nullable(),
    frontend_version: zod
        .string()
        .max(apiResourceDraftPartialUpdateResponseFrontendVersionMax)
        .nullish(),
    resourceinstanceid: zod.string().uuid().nullish(),
    created: zod.string().datetime({}),
    updated: zod.string().datetime({}),
});

/**
 * GET/PUT/PATCH/DELETE a single draft. PUT replaces the whole blob; PATCH
shallow-merges by section key -- untouched sections are kept, but a section
present in the body is replaced wholesale (no deep merge), so the client must
send the complete section, not just changed fields within it.
 */
export const apiResourceDraftDestroyParams = zod.object({
    graph_slug: zod.string(),
    id: zod.string().uuid(),
});
