"""
hca_permit graph spec.

AUTO-GENERATED by `manage.py generate_databc_views --from-db`.
Review cardinality, FLAT_GRAINS, and date formats before regenerating SQL.
"""

GRAPH_ID = 'f4b391f1-79d1-4886-ab2d-d72a197a9f21'
SCHEMA   = 'hca_permit'
SLUG     = 'per'

FLAT_GRAINS = []

# name, ngid, parent, cardinality, [(field, nodeid, dt, datefmt)]
NG = [
    ('permit_identification', '588c9c3c-df62-11ef-9ad0-0242ac170009', None, '1', [
        ('permit_number', '673aa382-df62-11ef-9ad0-0242ac170009', 'non-localized-string', None),
        ('issuing_agency', '7f0349ce-df62-11ef-9ad0-0242ac170009', 'reference', None),
        ('hca_permit_type', '9c8ad2f0-df62-11ef-9ad0-0242ac170009', 'reference', None),
        ('permit_holder', '3af6f67a-5926-11f0-bef3-0242ac170006', 'resource-instance-list', None),
    ]),
]
