"""
publication graph spec.

AUTO-GENERATED by `manage.py generate_databc_views --from-db`.
Review cardinality, FLAT_GRAINS, and date formats before regenerating SQL.
"""

GRAPH_ID = '3caf329f-b8f7-11e6-84a5-026d961c88e6'
SCHEMA   = 'publication'
SLUG     = 'pub'

FLAT_GRAINS = []

# name, ngid, parent, cardinality, [(field, nodeid, dt, datefmt)]
NG = [
    ('reference_link', '037c8f98-be00-11ed-8b5e-5254004d77d3', None, '1', [
        ('archaeological_sites', '20c23f8a-be00-11ed-bdf6-5254004d77d3', 'resource-instance-list', None),
        ('site_visits', '10517634-be00-11ed-b38b-5254004d77d3', 'resource-instance-list', None),
        ('repositories', '68b9813a-be01-11ed-8b5e-5254004d77d3', 'resource-instance-list', None),
    ]),
    ('information_carrier', '9f210d2d-e74a-11e6-84a6-026d961c88e6', None, 'n', [
        ('information_carrier', '9f210d2d-e74a-11e6-84a6-026d961c88e6', 'file-list', None),
    ]),
    ('copyright_type', 'a5f5c7b4-c40c-11ed-82cd-5254004d77d3', None, '1', [
        ('distribution_permitted', 'a5f5cc8c-c40c-11ed-82cd-5254004d77d3', 'boolean', None),
        ('signed_agreement', 'a5f5d268-c40c-11ed-82cd-5254004d77d3', 'file-list', None),
        ('agreement_text', 'a5f5d6fa-c40c-11ed-82cd-5254004d77d3', 'string', None),
        ('copyright_type', 'a5f5c7b4-c40c-11ed-82cd-5254004d77d3', 'reference', None),
    ]),
    ('keyword', 'b5f5b1ed-e74a-11e6-84a6-026d961c88e6', None, 'n', [
        ('keyword', 'b5f5b1ed-e74a-11e6-84a6-026d961c88e6', 'reference', None),
    ]),
    ('authors', 'c03e8f18-bc30-11ed-bf42-5254004d77d3', None, 'n', [
        ('other_authors_unlisted', '63f108ea-bdfb-11ed-a2b1-5254004d77d3', 'boolean', None),
        ('authors', 'c03e8f18-bc30-11ed-bf42-5254004d77d3', 'resource-instance-list', None),
    ]),
    ('publication_details', 'e9366370-bc33-11ed-bf42-5254004d77d3', None, '1', [
        ('title', '1930617c-c407-11ed-8154-5254004d77d3', 'string', None),
        ('page_range_end', '2d410f4c-bc3f-11ed-a483-5254004d77d3', 'number', None),
        ('other_journal_or_volume_name', '553a3d1a-bc36-11ed-a2df-5254004d77d3', 'string', None),
        ('journal_or_volume_name', 'c89a294c-bc35-11ed-9b80-5254004d77d3', 'resource-instance', None),
        ('publication_type', '83f08723-772b-456c-b693-863b0f84cb07', 'reference', None),
        ('page_range_start', 'd4f3cb86-bc3e-11ed-9b80-5254004d77d3', 'number', None),
        ('year_of_publication', '45216022-c409-11ed-81a5-5254004d77d3', 'date', 'YYYY-MM-DD'),
        ('publication_remarks', '289599a4-e307-4635-959e-7e415b0e8ec4', 'string', None),
    ]),
    ('publication_identifier', '63960b1a-bc3f-11ed-bd90-5254004d77d3', 'publication_details', 'n', [
        ('publication_identifier_type', '3604650c-2978-464a-83bb-fd559f7b9ea8', 'reference', None),
        ('publication_identifier', '63960b1a-bc3f-11ed-bd90-5254004d77d3', 'string', None),
    ]),
]
