"""
repository graph spec.

AUTO-GENERATED by `manage.py generate_databc_views --from-db`.
Review cardinality, FLAT_GRAINS, and date formats before regenerating SQL.
"""

GRAPH_ID = "3e6a2880-14d4-11ec-9df0-5254008afee6"
SCHEMA = "repository"
SLUG = "rep"

FLAT_GRAINS = []

# name, ngid, parent, cardinality, [(field, nodeid, dt, datefmt)]
NG = [
    (
        "contact_information",
        "ba927470-14d5-11ec-a57a-5254008afee6",
        None,
        "1",
        [
            ("city", "2e2e41aa-0b03-11ee-ae56-5254004d77d3", "string", None),
            ("province", "2e2e47e0-0b03-11ee-ae56-5254004d77d3", "reference", None),
            ("address_line_1", "2e2e4a74-0b03-11ee-ae56-5254004d77d3", "string", None),
            ("address_line_2", "2e2e51cc-0b03-11ee-ae56-5254004d77d3", "string", None),
            ("postal_code", "2e2e5488-0b03-11ee-ae56-5254004d77d3", "string", None),
            ("address_notes", "2e2e567c-0b03-11ee-ae56-5254004d77d3", "string", None),
            ("primary_email", "5c894e04-0aff-11ee-87c8-0050568377a0", "string", None),
            (
                "place_description",
                "ba927d08-14d5-11ec-a57a-5254008afee6",
                "string",
                None,
            ),
        ],
    ),
    (
        "repository_notes",
        "d435ce8a-ab99-11ec-affe-5254008afee6",
        None,
        "n",
        [
            ("note", "d435da38-ab99-11ec-affe-5254008afee6", "string", None),
        ],
    ),
    (
        "repository_identifier",
        "ea5a7956-14d4-11ec-aa11-5254008afee6",
        None,
        "1",
        [
            ("repository_name", "d10365ec-14e0-11ec-b5bf-5254008afee6", "string", None),
            (
                "repository_location_code",
                "5cf2771a-5cd5-11f0-b2bb-0242ac170007",
                "non-localized-string",
                None,
            ),
        ],
    ),
    (
        "physical_location",
        "ba9252e2-14d5-11ec-a57a-5254008afee6",
        "contact_information",
        "1",
        [
            (
                "physical_location",
                "ba9252e2-14d5-11ec-a57a-5254008afee6",
                "geojson-feature-collection",
                None,
            ),
        ],
    ),
    (
        "alternate_identifiers",
        "86bfd67c-d075-11ec-aae2-5254008afee6",
        "repository_identifier",
        "n",
        [
            ("alternate_name", "a1c04d76-d075-11ec-bb64-5254008afee6", "string", None),
            (
                "alternate_code",
                "9e83e43e-5cd5-11f0-b2bb-0242ac170007",
                "non-localized-string",
                None,
            ),
        ],
    ),
]
