-- GENERATED by manage.py generate_databc_views - do not edit.

CREATE OR REPLACE VIEW repository.resource_flat AS SELECT * FROM repository.mv_resource_flat;

COMMENT ON VIEW repository.resource_flat IS
'Flat repository records, one row per resource. Cardinality-n values are delimiter-joined text (" | " between tiles, "; " within a tile).';
