-- GENERATED by manage.py generate_databc_views - do not edit.
-- Graph 3e6a2880-14d4-11ec-9df0-5254008afee6
-- Requires 00_arches_util.sql to be applied first.
--
-- INVARIANTS:
--   * every key ALWAYS present; null, never absent.
--   * cardinality-n children are ALWAYS a jsonb array, [] when empty.
--   * cardinality-1 branches are an object, or null.
--   * array order is tiles.sortorder, then tileid.

SET client_min_messages = warning;
SET maintenance_work_mem = '512MB';
SET work_mem             = '128MB';

CREATE SCHEMA IF NOT EXISTS repository;

DROP MATERIALIZED VIEW IF EXISTS repository.mv_geom_physical_location CASCADE;
CREATE MATERIALIZED VIEW repository.mv_geom_physical_location AS
WITH per_tile AS (
    SELECT t.resourceinstanceid, t.tileid,
           ST_Collect(ST_Transform(g.geom, 4326)) AS geom
    FROM public.tiles t
    JOIN public.geojson_geometries g
      ON g.tileid = t.tileid AND g.nodeid = 'ba9252e2-14d5-11ec-a57a-5254008afee6'::uuid
    WHERE t.nodegroupid = 'ba9252e2-14d5-11ec-a57a-5254008afee6'::uuid
    GROUP BY t.resourceinstanceid, t.tileid
),
per_res AS (
    SELECT resourceinstanceid, ST_Collect(geom) AS raw
    FROM per_tile GROUP BY resourceinstanceid
),
fixed AS (
    SELECT resourceinstanceid, raw,
           ST_MakeValid(ST_CollectionHomogenize(ST_MakeValid(raw))) AS g
    FROM per_res
)
SELECT resourceinstanceid,
       g::geometry(Geometry, 4326)   AS physical_location_geom,
       ST_GeometryType(g)            AS physical_location_geom_type,
       ST_IsValid(raw)               AS physical_location_source_valid,
       (CASE WHEN ST_IsEmpty(ST_CollectionExtract(g, 1)) THEN NULL
             ELSE ST_CollectionExtract(g, 1) END)::geometry(MultiPoint, 4326)      AS physical_location_points,
       (CASE WHEN ST_IsEmpty(ST_CollectionExtract(g, 2)) THEN NULL
             ELSE ST_CollectionExtract(g, 2) END)::geometry(MultiLineString, 4326) AS physical_location_lines,
       (CASE WHEN ST_IsEmpty(ST_CollectionExtract(g, 3)) THEN NULL
             ELSE ST_CollectionExtract(g, 3) END)::geometry(MultiPolygon, 4326)    AS physical_location_polygons
FROM fixed;

CREATE UNIQUE INDEX mv_geom_physical_location_pk   ON repository.mv_geom_physical_location (resourceinstanceid);
CREATE INDEX mv_geom_physical_location_gix         ON repository.mv_geom_physical_location USING GIST (physical_location_geom);
CREATE INDEX mv_geom_physical_location_poly_gix    ON repository.mv_geom_physical_location USING GIST (physical_location_polygons);
CREATE INDEX mv_geom_physical_location_pt_gix      ON repository.mv_geom_physical_location USING GIST (physical_location_points);
CREATE INDEX mv_geom_physical_location_line_gix    ON repository.mv_geom_physical_location USING GIST (physical_location_lines);
