-- GENERATED by manage.py generate_databc_views - do not edit.
-- Graph 3e6a2880-14d4-11ec-9df0-5254008afee6
-- Requires 00_arches_util.sql to be applied first.
--
-- INVARIANTS:
--   * every key ALWAYS present; null, never absent.
--   * cardinality-n children are ALWAYS a jsonb array, [] when empty.
--   * cardinality-1 branches are an object, or null.
--   * array order is tiles.sortorder, then tileid.

SET client_min_messages = warning;
SET maintenance_work_mem = '512MB';
SET work_mem             = '128MB';

CREATE SCHEMA IF NOT EXISTS repository;

-- ---------------------------------------------------------------------
-- repository_notes  (cardinality n)
-- ---------------------------------------------------------------------
DROP MATERIALIZED VIEW IF EXISTS repository.mv_repository_notes CASCADE;
CREATE MATERIALIZED VIEW repository.mv_repository_notes AS
WITH repository_notes AS (
    SELECT t.resourceinstanceid AS resourceinstanceid,
           jsonb_agg(jsonb_build_object(
            'note', arches_util.i18n_text(t.tiledata -> 'd435da38-ab99-11ec-affe-5254008afee6')
        ) ORDER BY COALESCE(t.sortorder, 2147483647), t.tileid) AS arr
    FROM public.tiles t
    WHERE t.nodegroupid = 'd435ce8a-ab99-11ec-affe-5254008afee6'::uuid
    GROUP BY t.resourceinstanceid
)
SELECT resourceinstanceid, arr AS repository_notes FROM repository_notes;

CREATE UNIQUE INDEX mv_repository_notes_pk ON repository.mv_repository_notes (resourceinstanceid);
