-- GENERATED by manage.py generate_databc_views - do not edit.
-- Graph 3e6a2880-14d4-11ec-9df0-5254008afee6
-- Requires 00_arches_util.sql to be applied first.
--
-- INVARIANTS:
--   * every key ALWAYS present; null, never absent.
--   * cardinality-n children are ALWAYS a jsonb array, [] when empty.
--   * cardinality-1 branches are an object, or null.
--   * array order is tiles.sortorder, then tileid.

SET client_min_messages = warning;
SET maintenance_work_mem = '512MB';
SET work_mem             = '128MB';

CREATE SCHEMA IF NOT EXISTS repository;

DROP MATERIALIZED VIEW IF EXISTS repository.mv_resource CASCADE;
CREATE MATERIALIZED VIEW repository.mv_resource AS
-- resource_instances is the row driver: one row per resource including
-- resources with zero tiles; carries the graphid filter.
SELECT
    r.resourceinstanceid,
    b0.contact_information,
    COALESCE(b1.repository_notes, '[]'::jsonb) AS repository_notes,
    b2.repository_identifier,
    g_physical_location.physical_location_geom,
    g_physical_location.physical_location_geom_type,
    g_physical_location.physical_location_source_valid,
    g_physical_location.physical_location_points,
    g_physical_location.physical_location_lines,
    g_physical_location.physical_location_polygons,
    jsonb_build_object(
        'resourceinstanceid', r.resourceinstanceid,
        'contact_information', b0.contact_information,
        'repository_notes', COALESCE(b1.repository_notes, '[]'::jsonb),
        'repository_identifier', b2.repository_identifier
    ) AS resource
FROM public.resource_instances r
LEFT JOIN repository.mv_contact_information b0 ON b0.resourceinstanceid = r.resourceinstanceid
LEFT JOIN repository.mv_repository_notes b1 ON b1.resourceinstanceid = r.resourceinstanceid
LEFT JOIN repository.mv_repository_identifier b2 ON b2.resourceinstanceid = r.resourceinstanceid
LEFT JOIN repository.mv_geom_physical_location g_physical_location ON g_physical_location.resourceinstanceid = r.resourceinstanceid
WHERE r.graphid = '3e6a2880-14d4-11ec-9df0-5254008afee6'::uuid;

CREATE UNIQUE INDEX mv_resource_pk  ON repository.mv_resource (resourceinstanceid);
CREATE INDEX mv_resource_res        ON repository.mv_resource USING GIN (resource jsonb_path_ops);
CREATE INDEX mv_resource_physical_location_gix      ON repository.mv_resource USING GIST (physical_location_geom);
CREATE INDEX mv_resource_physical_location_poly_gix ON repository.mv_resource USING GIST (physical_location_polygons);
