-- GENERATED by manage.py generate_databc_views - do not edit.

CREATE OR REPLACE PROCEDURE repository.refresh_resource(concurrent boolean DEFAULT true)
LANGUAGE plpgsql AS $$
DECLARE
    mode text := CASE WHEN concurrent THEN 'CONCURRENTLY' ELSE '' END;
    mv   text;
BEGIN
    FOREACH mv IN ARRAY ARRAY[
        'repository.mv_geom_physical_location',
        'repository.mv_contact_information',
        'repository.mv_repository_notes',
        'repository.mv_repository_identifier',
        'repository.mv_resource'
    ]
    LOOP
        RAISE NOTICE 'refreshing %', mv;
        EXECUTE format('REFRESH MATERIALIZED VIEW %s %s', mode, mv);
        COMMIT;
    END LOOP;
END $$;
