-- GENERATED by manage.py generate_databc_views - do not edit.

CREATE OR REPLACE VIEW repository.resource AS SELECT * FROM repository.mv_resource;

COMMENT ON VIEW repository.resource IS
'Stable read contract for repository. One row per resource instance. Backed by mv_resource.';

-- GRANT SELECT ON repository.resource TO <app_role>;
