"""
Tests for the generate_databc_views management command.

The command always reads from the database (no --from-db flag).
_build_spec and SpecGenerator are patched in handle() tests so no DB is needed.
"""

import os
import tempfile
import types
from io import StringIO
from unittest.mock import Mock, mock_open, patch

from django.core.management import call_command
from django.core.management.base import CommandError
from django.test import SimpleTestCase, TestCase

from bcap.databc_config import GRAPHS
from bcap.management.commands.generate_databc_views import Command


def _cmd(**kwargs):
    return Command(stdout=StringIO(), stderr=StringIO(), **kwargs)


def _minimal_result(slug, schema):
    """Minimal result dict matching the shape returned by SpecGenerator.generate()."""
    return {
        "slug": slug,
        "schema": schema,
        "graph_id": "aaaa-bbbb-cccc-dddd",
        "tops": ["branch_one"],
        "geoms": [],
        "grains": [],
        "grain_view_names": {},
        "grain_tables": [],
        "res_cols": [],
    }


# ---------------------------------------------------------------------------
# _date_format
# ---------------------------------------------------------------------------


class TestDateFormat(SimpleTestCase):
    def _node(self, config):
        return Mock(config=config)

    def test_date_format_from_camel_case_key(self):
        self.assertEqual(
            _cmd()._date_format(self._node({"dateFormat": "DD/MM/YYYY"})), "DD/MM/YYYY"
        )

    def test_date_format_from_lowercase_key(self):
        self.assertEqual(
            _cmd()._date_format(self._node({"dateformat": "MM-YYYY"})), "MM-YYYY"
        )

    def test_camel_case_key_takes_priority_over_lowercase(self):
        self.assertEqual(
            _cmd()._date_format(
                self._node({"dateFormat": "YYYY", "dateformat": "other"})
            ),
            "YYYY",
        )

    def test_fallback_when_config_is_none(self):
        self.assertEqual(_cmd()._date_format(self._node(None)), "YYYY-MM-DD")

    def test_fallback_when_config_is_empty_dict(self):
        self.assertEqual(_cmd()._date_format(self._node({})), "YYYY-MM-DD")

    def test_fallback_when_key_absent(self):
        self.assertEqual(
            _cmd()._date_format(self._node({"unrelated": "value"})), "YYYY-MM-DD"
        )

    def test_fallback_when_date_format_is_empty_string(self):
        self.assertEqual(
            _cmd()._date_format(self._node({"dateFormat": ""})), "YYYY-MM-DD"
        )


# ---------------------------------------------------------------------------
# handle() — validation
# ---------------------------------------------------------------------------


class TestHandleValidation(TestCase):
    def test_unknown_slug_raises_command_error(self):
        with self.assertRaises(CommandError):
            call_command("generate_databc_views", "no_such_slug")

    def test_mixed_known_and_unknown_raises_command_error(self):
        with self.assertRaises(CommandError):
            call_command("generate_databc_views", "sv", "bad_slug")


# ---------------------------------------------------------------------------
# _write_sql_items
# ---------------------------------------------------------------------------


class TestWriteSqlItems(SimpleTestCase):
    """Unit tests for _write_sql_items output content (no DB required)."""

    def _write(self, results):
        with tempfile.NamedTemporaryFile(mode="w", suffix=".py", delete=False) as fh:
            path = fh.name
        try:
            _cmd()._write_sql_items(path, results)
            with open(path) as fh:
                return fh.read()
        finally:
            os.unlink(path)

    def _sv_result(self):
        return {"sv": _minimal_result("sv", "site_visit")}

    def test_generated_header_present(self):
        self.assertIn(
            "GENERATED by manage.py generate_databc_views",
            self._write(self._sv_result()),
        )

    def test_sql_items_list_present(self):
        self.assertIn("sql_items = [", self._write(self._sv_result()))

    def test_databc_arches_util_item_included(self):
        self.assertIn("databc_arches_util", self._write(self._sv_result()))

    def test_branch_mv_item_included(self):
        self.assertIn("sv_mv_branch_one", self._write(self._sv_result()))

    def test_resource_flat_item_included(self):
        self.assertIn("sv_mv_resource_flat", self._write(self._sv_result()))

    def test_api_view_item_included(self):
        self.assertIn("databc_site_visit", self._write(self._sv_result()))

    def test_grain_flat_item_included_when_grains_present(self):
        result = {
            "sv": {
                **_minimal_result("sv", "site_visit"),
                "grains": ["site_visit_location"],
                "grain_view_names": {},
            }
        }
        self.assertIn("sv_mv_site_visit_location_flat", self._write(result))

    def test_result_order_follows_graphs_config_order(self):
        """Items appear in GRAPHS dict order, not all_results insertion order."""
        both = {
            "as": _minimal_result("as", "archaeological_site"),
            "sv": _minimal_result("sv", "site_visit"),
        }
        content = self._write(both)
        # In GRAPHS, "sv" is defined before "as"
        sv_pos = content.index("sv_mv_resource_flat")
        as_pos = content.index("as_mv_resource_flat")
        self.assertLess(sv_pos, as_pos)

    def test_output_ends_with_newline(self):
        self.assertTrue(self._write(self._sv_result()).endswith("\n"))


# ---------------------------------------------------------------------------
# handle() — happy path (DB mocked out)
# ---------------------------------------------------------------------------


class TestHandleHappyPath(TestCase):
    """
    Tests for handle() orchestration logic.

    _build_spec and SpecGenerator are patched so no database is required.
    shutil.copy2 and builtins.open are also patched to avoid filesystem side effects.
    """

    def _run(self, *slugs):
        """
        Run the command for the given slugs with all external I/O mocked.
        Returns (stdout_str, mock_generator_instance).
        """
        fake_spec = types.SimpleNamespace(
            GRAPH_ID="fake-id",
            SCHEMA="site_visit",
            SLUG="sv",
            FLAT_GRAINS=[],
            FLAT_GRAIN_VIEW_NAMES={},
            NG=[],
        )
        mock_gen = Mock()
        mock_gen.generate.return_value = _minimal_result("sv", "site_visit")

        out = StringIO()
        with (
            patch.object(Command, "_build_spec", return_value=fake_spec),
            patch(
                "bcap.management.commands.generate_databc_views.SpecGenerator",
                return_value=mock_gen,
            ),
            patch("shutil.copy2"),
            patch("os.makedirs"),
            patch("builtins.open", mock_open()),
        ):
            call_command("generate_databc_views", *slugs, stdout=out)
        return out.getvalue(), mock_gen

    def test_output_written_message_present(self):
        out, _ = self._run("sv")
        self.assertIn("Output written to", out)

    def test_next_steps_message_present(self):
        out, _ = self._run("sv")
        self.assertIn("Next steps", out)

    def test_generate_called_for_every_slug_when_all_passed(self):
        _, mock_gen = self._run(*GRAPHS.keys())
        self.assertEqual(mock_gen.generate.call_count, len(GRAPHS))

    def test_all_slugs_run_without_error(self):
        self._run(*GRAPHS.keys())  # should not raise
