import contextlib
import os
import sys
import tempfile
from io import StringIO
from unittest.mock import Mock, mock_open, patch

from django.core.management import call_command
from django.core.management.base import CommandError
from django.test import SimpleTestCase, TestCase

from bcap.management.commands.generate_databc_views import (
    DATE_FORMAT_DEFAULT,
    GRAPH_SLUGS,
    Command,
)


def _cmd(**kwargs):
    return Command(stdout=StringIO(), stderr=StringIO(), **kwargs)


def _success_run():
    """Stub for subprocess.run that always succeeds."""
    return Mock(return_value=Mock(returncode=0, stdout="", stderr=""))


@contextlib.contextmanager
def _mocked_io(mock_subprocess=None, mock_regen=False):
    """
    Context manager that mocks all external I/O for generate_databc_views.

    Yields a namespace with .run (subprocess mock) and .regen (_regenerate_spec
    mock, only when mock_regen=True).
    """

    class _Mocks:
        pass

    ns = _Mocks()
    ns.run = mock_subprocess or _success_run()

    patches = [
        patch("subprocess.run", ns.run),
        patch("shutil.copy2"),
        patch("builtins.open", mock_open()),
        patch("os.makedirs"),
    ]
    if mock_regen:
        patches.append(patch.object(Command, "_regenerate_spec"))

    with contextlib.ExitStack() as stack:
        mocks = [stack.enter_context(p) for p in patches]
        ns.regen = mocks[4] if mock_regen else None
        yield ns


# ---------------------------------------------------------------------------
# _render_spec
# ---------------------------------------------------------------------------


class TestRenderSpec(SimpleTestCase):
    _GID = "aaaa-0000-bbbb-1111"
    _SCHEMA = "my_schema"
    _SLUG = "my_slug"
    _NG_LIST = [
        (
            "branch_one",
            "ng-uuid-1",
            None,
            "1",
            [
                ("field_a", "node-uuid-1", "string", None),
                ("start_date", "node-uuid-2", "date", "YYYY-MM-DD"),
            ],
        ),
        ("branch_two", "ng-uuid-2", "branch_one", "n", []),
    ]

    def _render(self, gid=None, schema=None, slug=None, flat_grains=None, ng_list=None):
        return _cmd()._render_spec(
            gid or self._GID,
            schema or self._SCHEMA,
            slug or self._SLUG,
            flat_grains if flat_grains is not None else [],
            ng_list if ng_list is not None else self._NG_LIST,
        )

    def test_output_ends_with_newline(self):
        self.assertTrue(self._render().endswith("\n"))

    def test_graph_id_present(self):
        self.assertIn(f"GRAPH_ID = '{self._GID}'", self._render())

    def test_schema_present(self):
        self.assertIn(f"SCHEMA   = '{self._SCHEMA}'", self._render())

    def test_slug_present(self):
        self.assertIn(f"SLUG     = '{self._SLUG}'", self._render())

    def test_flat_grains_empty_list(self):
        self.assertIn("FLAT_GRAINS = []", self._render(flat_grains=[]))

    def test_flat_grains_with_entries(self):
        self.assertIn(
            "FLAT_GRAINS = ['branch_a', 'branch_b']",
            self._render(flat_grains=["branch_a", "branch_b"]),
        )

    def test_ng_list_opened_and_closed(self):
        output = self._render()
        self.assertIn("NG = [", output)
        self.assertTrue(output.strip().endswith("]"))

    def test_header_docstring_present(self):
        output = self._render()
        self.assertIn('"""', output)
        self.assertIn(
            "AUTO-GENERATED by `manage.py generate_databc_views --from-db`", output
        )

    def test_nodegroup_with_no_fields_uses_compact_form(self):
        output = self._render()
        self.assertIn("('branch_two', 'ng-uuid-2', 'branch_one', 'n', []),", output)

    def test_nodegroup_with_fields_expands(self):
        output = self._render()
        self.assertIn("('branch_one', 'ng-uuid-1', None, '1', [", output)

    def test_non_date_field_has_none_datefmt(self):
        output = self._render()
        self.assertIn("('field_a', 'node-uuid-1', 'string', None),", output)

    def test_date_field_includes_format_string(self):
        output = self._render()
        self.assertIn("('start_date', 'node-uuid-2', 'date', 'YYYY-MM-DD'),", output)

    def test_top_level_nodegroup_parent_is_none(self):
        output = self._render()
        self.assertIn("None, '1', [", output)

    def test_child_nodegroup_parent_is_quoted_alias(self):
        output = self._render()
        self.assertIn("'branch_two', 'ng-uuid-2', 'branch_one'", output)

    def test_empty_ng_list_produces_valid_output(self):
        output = self._render(ng_list=[])
        self.assertIn("NG = [", output)
        self.assertIn(f"GRAPH_ID = '{self._GID}'", output)


# ---------------------------------------------------------------------------
# _date_format
# ---------------------------------------------------------------------------


class TestDateFormat(SimpleTestCase):
    def _node(self, config):
        return Mock(config=config)

    def test_date_format_from_camel_case_key(self):
        self.assertEqual(
            _cmd()._date_format(self._node({"dateFormat": "DD/MM/YYYY"})), "DD/MM/YYYY"
        )

    def test_date_format_from_lowercase_key(self):
        self.assertEqual(
            _cmd()._date_format(self._node({"dateformat": "MM-YYYY"})), "MM-YYYY"
        )

    def test_camel_case_key_takes_priority_over_lowercase(self):
        self.assertEqual(
            _cmd()._date_format(
                self._node({"dateFormat": "YYYY", "dateformat": "other"})
            ),
            "YYYY",
        )

    def test_fallback_when_config_is_none(self):
        self.assertEqual(_cmd()._date_format(self._node(None)), DATE_FORMAT_DEFAULT)

    def test_fallback_when_config_is_empty_dict(self):
        self.assertEqual(_cmd()._date_format(self._node({})), DATE_FORMAT_DEFAULT)

    def test_fallback_when_key_absent(self):
        self.assertEqual(
            _cmd()._date_format(self._node({"unrelated": "value"})), DATE_FORMAT_DEFAULT
        )

    def test_fallback_when_date_format_is_empty_string(self):
        self.assertEqual(
            _cmd()._date_format(self._node({"dateFormat": ""})), DATE_FORMAT_DEFAULT
        )


# ---------------------------------------------------------------------------
# _format_with_black
# ---------------------------------------------------------------------------


class TestFormatWithBlack(SimpleTestCase):
    def test_no_stderr_output_on_success(self):
        cmd = _cmd()
        with patch("subprocess.run", return_value=Mock(returncode=0, stderr="")):
            cmd._format_with_black("/path/spec.py")
        self.assertEqual(cmd.stderr.getvalue(), "")

    def test_warning_written_on_nonzero_returncode(self):
        cmd = _cmd(no_color=True)
        with patch(
            "subprocess.run", return_value=Mock(returncode=1, stderr="syntax error")
        ):
            cmd._format_with_black("/path/spec.py")
        self.assertIn("black could not format", cmd.stderr.getvalue())

    def test_warning_includes_black_stderr_text(self):
        cmd = _cmd(no_color=True)
        with patch("subprocess.run", return_value=Mock(returncode=1, stderr="oh no")):
            cmd._format_with_black("/path/spec.py")
        self.assertIn("oh no", cmd.stderr.getvalue())

    def test_invokes_black_module_with_quiet_and_path(self):
        with patch("subprocess.run") as mock_run:
            mock_run.return_value = Mock(returncode=0, stderr="")
            _cmd()._format_with_black("/path/to/spec.py")
        argv = mock_run.call_args[0][0]
        self.assertEqual(argv[0], sys.executable)
        self.assertIn("-m", argv)
        self.assertIn("black", argv)
        self.assertIn("--quiet", argv)
        self.assertIn("/path/to/spec.py", argv)


# ---------------------------------------------------------------------------
# _load_existing_spec
# ---------------------------------------------------------------------------


class TestLoadExistingSpec(SimpleTestCase):
    def test_returns_empty_dict_when_file_missing(self):
        result = _cmd()._load_existing_spec("sv", "/nonexistent/dir")
        self.assertEqual(result, {})

    def test_returns_slug_and_flat_grains_from_file(self):
        spec_src = (
            "SLUG = 'site_visit'\n"
            "FLAT_GRAINS = ['branch_a', 'branch_b']\n"
            "NG = []\n"
        )
        with tempfile.TemporaryDirectory() as tmpdir:
            with open(os.path.join(tmpdir, "sv_spec.py"), "w") as fh:
                fh.write(spec_src)
            result = _cmd()._load_existing_spec("sv", tmpdir)
        self.assertEqual(result["SLUG"], "site_visit")
        self.assertEqual(result["FLAT_GRAINS"], ["branch_a", "branch_b"])

    def test_missing_attributes_use_defaults(self):
        # A spec with no SLUG or FLAT_GRAINS defined.
        with tempfile.TemporaryDirectory() as tmpdir:
            with open(os.path.join(tmpdir, "sv_spec.py"), "w") as fh:
                fh.write("NG = []\n")
            result = _cmd()._load_existing_spec("sv", tmpdir)
        self.assertEqual(result["SLUG"], "sv")
        self.assertEqual(result["FLAT_GRAINS"], [])


# ---------------------------------------------------------------------------
# _regenerate_spec — _format_with_black is called after the file is written
# ---------------------------------------------------------------------------


class TestRegenerateSpecCallsBlack(SimpleTestCase):
    """
    Unit-test _regenerate_spec in isolation.

    All DB queries, file I/O, and the black formatter are mocked so that
    we can verify _format_with_black is invoked exactly once after the spec
    file is written, and that the path passed to it ends with '<slug>_spec.py'.
    """

    def _make_graph(self, slug="site-visit", graphid="gid-0000"):
        g = Mock()
        g.graphid = graphid
        g.slug = slug
        g.name = "Site Visit"
        return g

    def _make_node(
        self, alias, nodeid, datatype="string", istopnode=False, ng_id="ng-000"
    ):
        n = Mock()
        n.alias = alias
        n.nodeid = nodeid
        n.datatype = datatype
        n.istopnode = istopnode
        n.nodegroup_id = ng_id
        n.sortorder = 0
        n.config = None
        return n

    def _make_ng(self, ngid, parent_id=None, cardinality="1"):
        ng = Mock()
        ng.nodegroupid = ngid
        ng.parentnodegroup_id = parent_id
        ng.cardinality = cardinality
        return ng

    def test_format_with_black_called_after_spec_written(self):
        root_node = self._make_node(
            "root", "root-ng-id", "semantic", istopnode=True, ng_id="root-ng-id"
        )
        branch_node = self._make_node(
            "my_branch", "branch-ng-id", "semantic", ng_id="branch-ng-id"
        )
        field_node = self._make_node(
            "my_field", "field-node-id", "string", ng_id="branch-ng-id"
        )

        root_ng = self._make_ng("root-ng-id")
        branch_ng = self._make_ng("branch-ng-id", parent_id="root-ng-id")

        cmd = _cmd()

        with (
            patch(
                "bcap.management.commands.generate_databc_views.GraphModel"
            ) as MockGM,
            patch("bcap.management.commands.generate_databc_views.Node") as MockNode,
            patch("bcap.management.commands.generate_databc_views.NodeGroup") as MockNG,
            patch("builtins.open", mock_open()),
            patch.object(
                cmd,
                "_load_existing_spec",
                return_value={"SLUG": "sv", "FLAT_GRAINS": []},
            ),
            patch.object(cmd, "_format_with_black") as mock_black,
        ):
            MockGM.objects.get.return_value = self._make_graph()
            (
                MockNode.objects.filter.return_value.select_related.return_value.order_by.return_value
            ) = [root_node, branch_node, field_node]
            (
                MockNG.objects.filter.return_value.distinct.return_value.select_related.return_value
            ) = [root_ng, branch_ng]

            with tempfile.TemporaryDirectory() as tmpdir:
                cmd._regenerate_spec("sv", tmpdir)

        mock_black.assert_called_once()
        called_path = mock_black.call_args[0][0]
        self.assertTrue(
            called_path.endswith("sv_spec.py"),
            f"Expected path ending with 'sv_spec.py', got: {called_path}",
        )

    def test_format_with_black_called_with_written_file_path(self):
        """The path passed to _format_with_black is the path used to open() the file."""
        root_node = self._make_node(
            "root", "root-ng-id", "semantic", istopnode=True, ng_id="root-ng-id"
        )
        branch_ng = self._make_ng("branch-ng-id", parent_id="root-ng-id")
        root_ng = self._make_ng("root-ng-id")

        cmd = _cmd()
        opened_paths = []

        real_open = open

        def capturing_open(path, *args, **kwargs):
            if isinstance(path, str) and path.endswith(".py"):
                opened_paths.append(path)
            return mock_open()(path, *args, **kwargs)

        with (
            patch(
                "bcap.management.commands.generate_databc_views.GraphModel"
            ) as MockGM,
            patch("bcap.management.commands.generate_databc_views.Node") as MockNode,
            patch("bcap.management.commands.generate_databc_views.NodeGroup") as MockNG,
            patch("builtins.open", side_effect=capturing_open),
            patch.object(
                cmd,
                "_load_existing_spec",
                return_value={"SLUG": "sv", "FLAT_GRAINS": []},
            ),
            patch.object(cmd, "_format_with_black") as mock_black,
        ):
            MockGM.objects.get.return_value = self._make_graph()
            (
                MockNode.objects.filter.return_value.select_related.return_value.order_by.return_value
            ) = [root_node]
            (
                MockNG.objects.filter.return_value.distinct.return_value.select_related.return_value
            ) = [root_ng, branch_ng]

            with tempfile.TemporaryDirectory() as tmpdir:
                cmd._regenerate_spec("sv", tmpdir)

        black_path = mock_black.call_args[0][0]
        self.assertIn(black_path, opened_paths)


# ---------------------------------------------------------------------------
# Command.handle — orchestration
# ---------------------------------------------------------------------------


class TestGenerateDatabcViewsCommand(TestCase):
    """
    Tests for the generate_databc_views management command.

    All subprocess calls (generate.py), shutil.copy2, and file I/O are mocked.
    _regenerate_spec is patched where the test is about orchestration rather
    than spec-generation logic (which is covered by TestRegenerateSpecCallsBlack).
    """

    # --- error cases -------------------------------------------------------

    def test_unknown_slug_raises_command_error(self):
        with self.assertRaises(CommandError):
            call_command("generate_databc_views", "no_such_slug")

    def test_mixed_known_and_unknown_raises_command_error(self):
        with self.assertRaises(CommandError):
            call_command("generate_databc_views", "sv", "bad_slug")

    def test_generate_script_failure_raises_command_error(self):
        failing = Mock(return_value=Mock(returncode=1, stdout="", stderr="error"))
        with _mocked_io(mock_subprocess=failing):
            with self.assertRaises(CommandError):
                call_command("generate_databc_views", "sv")

    # --- single graph argument ---------------------------------------------

    def test_single_graph_calls_generate_script_once(self):
        with _mocked_io() as m:
            call_command("generate_databc_views", "sv")
        self.assertEqual(m.run.call_count, 1)

    def test_single_graph_passes_correct_spec_arg(self):
        with _mocked_io() as m:
            call_command("generate_databc_views", "as")
        argv = m.run.call_args[0][0]
        self.assertIn("as_spec", argv)

    def test_two_graphs_calls_generate_script_twice(self):
        with _mocked_io() as m:
            call_command("generate_databc_views", "sv", "as")
        self.assertEqual(m.run.call_count, 2)

    # --- default: all known graphs -----------------------------------------

    def test_default_processes_every_known_graph(self):
        with _mocked_io() as m:
            call_command("generate_databc_views")
        self.assertEqual(m.run.call_count, len(GRAPH_SLUGS))

    def test_default_includes_all_known_spec_args(self):
        with _mocked_io() as m:
            call_command("generate_databc_views")
        spec_args = {call[0][0][2] for call in m.run.call_args_list}
        for slug in GRAPH_SLUGS:
            self.assertIn(f"{slug}_spec", spec_args)

    # --- stdout summary ----------------------------------------------------

    def test_stdout_reports_output_written(self):
        out = StringIO()
        with _mocked_io():
            call_command("generate_databc_views", "sv", stdout=out)
        self.assertIn("Output written to", out.getvalue())

    def test_stdout_reports_next_steps(self):
        out = StringIO()
        with _mocked_io():
            call_command("generate_databc_views", "sv", stdout=out)
        self.assertIn("Next steps", out.getvalue())

    # --- --from-db flag: _regenerate_spec orchestration -------------------

    def test_from_db_calls_regenerate_spec_for_requested_graph(self):
        with _mocked_io(mock_regen=True) as m:
            call_command("generate_databc_views", "sv", "--from-db")
        m.regen.assert_called_once()
        self.assertEqual(m.regen.call_args[0][0], "sv")

    def test_from_db_calls_regenerate_spec_for_all_graphs_by_default(self):
        with _mocked_io(mock_regen=True) as m:
            call_command("generate_databc_views", "--from-db")
        self.assertEqual(m.regen.call_count, len(GRAPH_SLUGS))

    def test_without_from_db_does_not_call_regenerate_spec(self):
        with _mocked_io(mock_regen=True) as m:
            call_command("generate_databc_views", "sv")
        m.regen.assert_not_called()

    def test_from_db_still_runs_generate_script_after_regen(self):
        with _mocked_io(mock_regen=True) as m:
            call_command("generate_databc_views", "sv", "--from-db")
        self.assertEqual(m.run.call_count, 1)
