name: Prepare release

on:
  push:
    branches:
      - 'release_alpha'
      - 'release_beta'
      - 'release_patch'
      - 'release_minor'
      - 'release_major'

permissions:
  contents: write
  pull-requests: write

jobs:
  increment_version_and_pr:
    uses: bcgov/bcgov-arches-common/.github/workflows/release_prep_common.yml@main
    with:
      github-repo: bcgov/bcfms
    secrets:
      token: ${{ secrets.PROJECT_PAT }}
